<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InsertDataParroquiaWithSql extends Migration
{
    
    public function up()
    {
        DB::statement("
            INSERT INTO parroquia (nombre, defecto, provincia_id, status) VALUES
            ('EL CONDADO', 1, 1, 1),
            ('COTOCOLLAO', 0, 1, 1),
            ('BELLAVISTA', 0, 1, 1),
            ('CAÑARIBAMBA', 0, 1, 1),
            ('EL BATÁN', 0, 1, 1),
            ('PORTOVIEJO', 0, 1, 1),
            ('EL SAGRARIO', 0, 1, 1),
            ('EL VECINO', 0, 1, 1),
            ('GIL RAMÍREZ DÁVALOS', 0, 1, 1),
            ('HUAYNACÁPAC', 0, 1, 1),
            ('MACHÁNGARA', 0, 1, 1),
            ('MONAY', 0, 1, 1),
            ('SAN BLAS', 0, 1, 1),
            ('SAN SEBASTIÁN', 0, 1, 1),
            ('SUCRE', 0, 1, 1),
            ('TOTORACOCHA', 0, 1, 1),
            ('YANUNCAY', 0, 1, 1),
            ('HERMANO MIGUEL', 0, 1, 1),
            ('CUENCA', 0, 1, 1),
            ('BAÑOS', 0, 1, 1),
            ('CUMBE', 0, 1, 1),
            ('CHAUCHA', 0, 1, 1),
            ('CHECA (JIDCAY)', 0, 1, 1),
            ('CHIQUINTAD', 0, 1, 1),
            ('LLACAO', 0, 1, 1),
            ('MOLLETURO', 0, 1, 1),
            ('NULTI', 0, 1, 1),
            ('OCTAVIO CORDERO PALACIOS (SANTA ROSA)', 0, 1, 1),
            ('PACCHA', 0, 1, 1),
            ('QUINGEO', 0, 1, 1),
            ('RICAURTE', 0, 1, 1),
            ('SAN JOAQUÍN', 0, 1, 1),
            ('SANTA ANA', 0, 1, 1),
            ('SAYAUSÍ', 0, 1, 1),
            ('SIDCAY', 0, 1, 1),
            ('SININCAY', 0, 1, 1),
            ('TARQUI', 0, 1, 1),
            ('TURI', 0, 1, 1),
            ('VALLE', 0, 1, 1),
            ('VICTORIA DEL PORTETE (IRQUIS)', 0, 1, 1),
            ('GIRÓN', 0, 1, 1),
            ('ASUNCIÓN', 0, 1, 1),
            ('SAN GERARDO', 0, 1, 1),
            ('GUALACEO', 0, 1, 1),
            ('CHORDELEG', 0, 1, 1),
            ('DANIEL CÓRDOVA TORAL (EL ORIENTE)', 0, 1, 1),
            ('JADÁN', 0, 1, 1),
            ('MARIANO MORENO', 0, 1, 1),
            ('PRINCIPAL', 0, 1, 1),
            ('REMIGIO CRESPO TORAL (GÚLAG)', 0, 1, 1),
            ('SAN JUAN', 0, 1, 1),
            ('ZHIDMAD', 0, 1, 1),
            ('LUIS CORDERO VEGA', 0, 1, 1),
            ('SIMÓN BOLÍVAR (CAB. EN GAÑANZOL)', 0, 1, 1),
            ('NABÓN', 0, 1, 1),
            ('COCHAPATA', 0, 1, 1),
            ('EL PROGRESO (CAB.EN ZHOTA)', 0, 1, 1),
            ('LAS NIEVES (CHAYA)', 0, 1, 1),
            ('OÑA', 0, 1, 1),
            ('PAUTE', 0, 1, 1),
            ('AMALUZA', 0, 1, 1),
            ('BULÁN (JOSÉ VÍCTOR IZQUIERDO)', 0, 1, 1),
            ('CHICÁN (GUILLERMO ORTEGA)', 0, 1, 1),
            ('EL CABO', 0, 1, 1),
            ('GUACHAPALA', 0, 1, 1),
            ('GUARAINAG', 0, 1, 1),
            ('PALMAS', 0, 1, 1),
            ('PAN', 0, 1, 1),
            ('SAN CRISTÓBAL (CARLOS ORDÓÑEZ LAZO)', 0, 1, 1),
            ('SEVILLA DE ORO', 0, 1, 1),
            ('TOMEBAMBA', 0, 1, 1),
            ('DUG DUG', 0, 1, 1),
            ('PUCARÁ', 0, 1, 1),
            ('CAMILO PONCE ENRÍQUEZ (CAB. EN RÍO 7 DE MOLLEPONGO)', 0, 1, 1),
            ('SAN RAFAEL DE SHARUG', 0, 1, 1),
            ('SAN FERNANDO', 0, 1, 1),
            ('CHUMBLÍN', 0, 1, 1),
            ('SANTA ISABEL (CHAGUARURCO)', 0, 1, 1),
            ('ABDÓN CALDERÓN (LA UNIÓN)', 0, 1, 1),
            ('EL CARMEN DE PIJILÍ', 0, 1, 1),
            ('ZHAGLLI (SHAGLLI)', 0, 1, 1),
            ('SAN SALVADOR DE CAÑARIBAMBA', 0, 1, 1),
            ('SIGSIG', 0, 1, 1),
            ('CUCHIL (CUTCHIL)', 0, 1, 1),
            ('GIMA', 0, 1, 1),
            ('GUEL', 0, 1, 1),
            ('LUDO', 0, 1, 1),
            ('SAN BARTOLOMÉ', 0, 1, 1),
            ('SAN JOSÉ DE RARANGA', 0, 1, 1),
            ('SAN FELIPE DE OÑA CABECERA CANTONAL', 0, 1, 1),
            ('SUSUDEL', 0, 1, 1),
            ('CHORDELEG', 0, 1, 1),
            ('PRINCIPAL', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('LUIS GALARZA ORELLANA (CAB.EN DELEGSOL)', 0, 1, 1),
            ('SAN MARTÍN DE PUZHIO', 0, 1, 1),
            ('EL PAN', 0, 1, 1),
            ('AMALUZA', 0, 1, 1),
            ('PALMAS', 0, 1, 1),
            ('SAN VICENTE', 0, 1, 1),
            ('SEVILLA DE ORO', 0, 1, 1),
            ('AMALUZA', 0, 1, 1),
            ('PALMAS', 0, 1, 1),
            ('GUACHAPALA GUACHAPALA', 0, 1, 1),
            ('CAMILO PONCE ENRÍQUEZ CAMILO PONCE ENRÍQUEZ', 0, 1, 1),
            ('CAMILO PONCE ENRÍQUEZ EL CARMEN DE PIJILÍ', 0, 1, 1),
            ('ÁNGEL POLIBIO CHÁVES', 0, 1, 1),
            ('GABRIEL IGNACIO VEINTIMILLA', 0, 1, 1),
            ('GUANUJO', 0, 1, 1),
            ('GUARANDA', 0, 1, 1),
            ('FACUNDO VELA', 0, 1, 1),
            ('GUANUJO', 0, 1, 1),
            ('JULIO E. MORENO (CATANAHUÁN GRANDE)', 0, 1, 1),
            ('LAS NAVES', 0, 1, 1),
            ('SALINAS', 0, 1, 1),
            ('SAN LORENZO', 0, 1, 1),
            ('SAN SIMÓN (YACOTO)', 0, 1, 1),
            ('SANTA FÉ (SANTA FÉ)', 0, 1, 1),
            ('SIMIÁTUG', 0, 1, 1),
            ('SAN LUIS DE PAMBIL', 0, 1, 1),
            ('CHILLANES', 0, 1, 1),
            ('SAN JOSÉ DEL TAMBO (TAMBOPAMBA)', 0, 1, 1),
            ('SAN JOSÉ DE CHIMBO', 0, 1, 1),
            ('ASUNCIÓN (ASANCOTO)', 0, 1, 1),
            ('CALUMA', 0, 1, 1),
            ('MAGDALENA (CHAPACOTO)', 0, 1, 1),
            ('SAN SEBASTIÁN', 0, 1, 1),
            ('TELIMBELA', 0, 1, 1),
            ('ECHEANDÍA ECHEANDÍA', 0, 1, 1),
            ('SAN MIGUEL SAN MIGUEL', 0, 1, 1),
            ('SAN MIGUEL BALSAPAMBA', 0, 1, 1),
            ('SAN MIGUEL BILOVÁN', 0, 1, 1),
            ('SAN MIGUEL RÉGULO DE MORA', 0, 1, 1),
            ('SAN MIGUEL SAN PABLO (SAN PABLO DE ATENAS)', 0, 1, 1),
            ('SAN MIGUEL SANTIAGO', 0, 1, 1),
            ('SAN MIGUEL SAN VICENTE', 0, 1, 1),
            ('CALUMA CALUMA', 0, 1, 1),
            ('LAS NAVES LAS MERCEDES', 0, 1, 1),
            ('LAS NAVES LAS NAVES', 0, 1, 1),
            ('LAS NAVES LAS NAVES', 0, 1, 1),
            ('AURELIO BAYAS MARTÍNEZ', 0, 1, 1),
            ('AZOGUES', 0, 1, 1),
            ('BORRERO', 0, 1, 1),
            ('SAN FRANCISCO', 0, 1, 1),
            ('AZOGUES', 0, 1, 1),
            ('COJITAMBO', 0, 1, 1),
            ('DÉLEG', 0, 1, 1),
            ('GUAPÁN', 0, 1, 1),
            ('JAVIER LOYOLA (CHUQUIPATA)', 0, 1, 1),
            ('LUIS CORDERO', 0, 1, 1),
            ('PINDILIG', 0, 1, 1),
            ('RIVERA', 0, 1, 1),
            ('SAN MIGUEL', 0, 1, 1),
            ('SOLANO', 0, 1, 1),
            ('TADAY', 0, 1, 1),
            ('BIBLIÁN', 0, 1, 1),
            ('NAZÓN (CAB. EN PAMPA DE DOMÍNGUEZ)', 0, 1, 1),
            ('SAN FRANCISCO DE SAGEO', 0, 1, 1),
            ('TURUPAMBA', 0, 1, 1),
            ('JERUSALÉN', 0, 1, 1),
            ('CAÑAR', 0, 1, 1),
            ('CHONTAMARCA', 0, 1, 1),
            ('CHOROCOPTE', 0, 1, 1),
            ('GENERAL MORALES (SOCARTE)', 0, 1, 1),
            ('GUALLETURO', 0, 1, 1),
            ('HONORATO VÁSQUEZ (TAMBO VIEJO)', 0, 1, 1),
            ('INGAPIRCA', 0, 1, 1),
            ('JUNCAL', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('SUSCAL', 0, 1, 1),
            ('TAMBO', 0, 1, 1),
            ('ZHUD', 0, 1, 1),
            ('VENTURA', 0, 1, 1),
            ('DUCUR', 0, 1, 1),
            ('LA TRONCAL', 0, 1, 1),
            ('MANUEL J. CALLE', 0, 1, 1),
            ('PANCHO NEGRO', 0, 1, 1),
            ('EL TAMBO EL TAMBO', 0, 1, 1),
            ('DÉLEG DÉLEG', 0, 1, 1),
            ('DÉLEG SOLANO', 0, 1, 1),
            ('SUSCAL SUSCAL', 0, 1, 1),
            ('GONZÁLEZ SUÁREZ', 0, 1, 1),
            ('TULCÁN', 0, 1, 1),
            ('TULCÁN', 0, 1, 1),
            ('EL CARMELO (EL PUN)', 0, 1, 1),
            ('HUACA', 0, 1, 1),
            ('JULIO ANDRADE (OREJUELA)', 0, 1, 1),
            ('MALDONADO', 0, 1, 1),
            ('PIOTER', 0, 1, 1),
            ('TOBAR DONOSO (LA BOCANA DE CAMUMBÍ)', 0, 1, 1),
            ('TUFIÑO', 0, 1, 1),
            ('URBINA (TAYA)', 0, 1, 1),
            ('EL CHICAL', 0, 1, 1),
            ('MARISCAL SUCRE', 0, 1, 1),
            ('SANTA MARTHA DE CUBA', 0, 1, 1),
            ('BOLÍVAR', 0, 1, 1),
            ('GARCÍA MORENO', 0, 1, 1),
            ('LOS ANDES', 0, 1, 1),
            ('MONTE OLIVO', 0, 1, 1),
            ('SAN VICENTE DE PUSIR', 0, 1, 1),
            ('SAN RAFAEL', 0, 1, 1),
            ('EL ÁNGEL', 0, 1, 1),
            ('27 DE SEPTIEMBRE', 0, 1, 1),
            ('EL ANGEL', 0, 1, 1),
            ('EL GOALTAL', 0, 1, 1),
            ('LA LIBERTAD (ALIZO)', 0, 1, 1),
            ('SAN ISIDRO', 0, 1, 1),
            ('MIRA (CHONTAHUASI)', 0, 1, 1),
            ('CONCEPCIÓN', 0, 1, 1),
            ('JIJÓN Y CAAMAÑO (CAB. EN RÍO BLANCO)', 0, 1, 1),
            ('JUAN MONTALVO (SAN IGNACIO DE QUIL)', 0, 1, 1),
            ('GONZÁLEZ SUÁREZ', 0, 1, 1),
            ('SAN JOSÉ', 0, 1, 1),
            ('SAN GABRIEL', 0, 1, 1),
            ('CRISTÓBAL COLÓN', 0, 1, 1),
            ('CHITÁN DE NAVARRETE', 0, 1, 1),
            ('FERNÁNDEZ SALVADOR', 0, 1, 1),
            ('LA PAZ', 0, 1, 1),
            ('PIARTAL', 0, 1, 1),
            ('HUACA', 0, 1, 1),
            ('MARISCAL SUCRE', 0, 1, 1),
            ('ELOY ALFARO (SAN FELIPE)', 0, 1, 1),
            ('IGNACIO FLORES (PARQUE FLORES)', 0, 1, 1),
            ('JUAN MONTALVO (SAN SEBASTIÁN)', 0, 1, 1),
            ('LA MATRIZ', 0, 1, 1),
            ('SAN BUENAVENTURA', 0, 1, 1),
            ('LATACUNGA', 0, 1, 1),
            ('ALAQUES (ALÁQUEZ)', 0, 1, 1),
            ('BELISARIO QUEVEDO (GUANAILÍN)', 0, 1, 1),
            ('GUAITACAMA (GUAYTACAMA)', 0, 1, 1),
            ('JOSEGUANGO BAJO', 0, 1, 1),
            ('LAS PAMPAS', 0, 1, 1),
            ('MULALÓ', 0, 1, 1),
            ('11 DE NOVIEMBRE (ILINCHISI)', 0, 1, 1),
            ('POALÓ', 0, 1, 1),
            ('SAN JUAN DE PASTOCALLE', 0, 1, 1),
            ('SIGCHOS', 0, 1, 1),
            ('TANICUCHÍ', 0, 1, 1),
            ('TOACASO', 0, 1, 1),
            ('PALO QUEMADO', 0, 1, 1),
            ('EL CARMEN', 0, 1, 1),
            ('LA MANÁ', 0, 1, 1),
            ('EL TRIUNFO', 0, 1, 1),
            ('LA MANÁ', 0, 1, 1),
            ('GUASAGANDA (CAB.EN GUASAGANDA', 0, 1, 1),
            ('PUCAYACU', 0, 1, 1),
            ('EL CORAZÓN', 0, 1, 1),
            ('MORASPUNGO', 0, 1, 1),
            ('PINLLOPATA', 0, 1, 1),
            ('RAMÓN CAMPAÑA', 0, 1, 1),
            ('PUJILÍ', 0, 1, 1),
            ('ANGAMARCA', 0, 1, 1),
            ('CHUCCHILÁN (CHUGCHILÁN)', 0, 1, 1),
            ('GUANGAJE', 0, 1, 1),
            ('ISINLIBÍ (ISINLIVÍ)', 0, 1, 1),
            ('LA VICTORIA', 0, 1, 1),
            ('PILALÓ', 0, 1, 1),
            ('TINGO', 0, 1, 1),
            ('ZUMBAHUA', 0, 1, 1),
            ('SAN MIGUEL', 0, 1, 1),
            ('ANTONIO JOSÉ HOLGUÍN (SANTA LUCÍA)', 0, 1, 1),
            ('CUSUBAMBA', 0, 1, 1),
            ('MULALILLO', 0, 1, 1),
            ('MULLIQUINDIL (SANTA ANA)', 0, 1, 1),
            ('PANSALEO', 0, 1, 1),
            ('SAQUISILÍ', 0, 1, 1),
            ('CANCHAGUA', 0, 1, 1),
            ('CHANTILÍN', 0, 1, 1),
            ('COCHAPAMBA', 0, 1, 1),
            ('SIGCHOS', 0, 1, 1),
            ('CHUGCHILLÁN', 0, 1, 1),
            ('ISINLIVÍ', 0, 1, 1),
            ('LAS PAMPAS', 0, 1, 1),
            ('PALO QUEMADO', 0, 1, 1),
            ('LIZARZABURU', 0, 1, 1),
            ('MALDONADO', 0, 1, 1),
            ('VELASCO', 0, 1, 1),
            ('VELOZ', 0, 1, 1),
            ('YARUQUÍES', 0, 1, 1),
            ('RIOBAMBA', 0, 1, 1),
            ('CACHA (CAB. EN MACHÁNGARA)', 0, 1, 1),
            ('CALPI', 0, 1, 1),
            ('CUBIJÍES', 0, 1, 1),
            ('FLORES', 0, 1, 1),
            ('LICÁN', 0, 1, 1),
            ('LICTO', 0, 1, 1),
            ('PUNGALÁ', 0, 1, 1),
            ('PUNÍN', 0, 1, 1),
            ('QUIMIAG', 0, 1, 1),
            ('SAN JUAN', 0, 1, 1),
            ('SAN LUIS', 0, 1, 1),
            ('ALAUSÍ', 0, 1, 1),
            ('ACHUPALLAS', 0, 1, 1),
            ('CUMANDÁ', 0, 1, 1),
            ('GUASUNTOS', 0, 1, 1),
            ('HUIGRA', 0, 1, 1),
            ('MULTITUD', 0, 1, 1),
            ('PISTISHÍ (NARIZ DEL DIABLO)', 0, 1, 1),
            ('PUMALLACTA', 0, 1, 1),
            ('SEVILLA', 0, 1, 1),
            ('SIBAMBE', 0, 1, 1),
            ('TIXÁN', 0, 1, 1),
            ('CAJABAMBA', 0, 1, 1),
            ('SICALPA', 0, 1, 1),
            ('VILLA LA UNIÓN (CAJABAMBA)', 0, 1, 1),
            ('CAÑI', 0, 1, 1),
            ('COLUMBE', 0, 1, 1),
            ('JUAN DE VELASCO (PANGOR)', 0, 1, 1),
            ('SANTIAGO DE QUITO (CAB. EN SAN ANTONIO DE QUITO)', 0, 1, 1),
            ('CHAMBO', 0, 1, 1),
            ('CHUNCHI', 0, 1, 1),
            ('CAPZOL', 0, 1, 1),
            ('COMPUD', 0, 1, 1),
            ('GONZOL', 0, 1, 1),
            ('LLAGOS', 0, 1, 1),
            ('GUAMOTE', 0, 1, 1),
            ('CEBADAS', 0, 1, 1),
            ('PALMIRA', 0, 1, 1),
            ('EL ROSARIO', 0, 1, 1),
            ('LA MATRIZ', 0, 1, 1),
            ('GUANO', 0, 1, 1),
            ('GUANANDO', 0, 1, 1),
            ('ILAPO', 0, 1, 1),
            ('LA PROVIDENCIA', 0, 1, 1),
            ('SAN ANDRÉS', 0, 1, 1),
            ('SAN GERARDO DE PACAICAGUÁN', 0, 1, 1),
            ('SAN ISIDRO DE PATULÚ', 0, 1, 1),
            ('SAN JOSÉ DEL CHAZO', 0, 1, 1),
            ('SANTA FÉ DE GALÁN', 0, 1, 1),
            ('VALPARAÍSO', 0, 1, 1),
            ('PALLATANGA', 0, 1, 1),
            ('PENIPE', 0, 1, 1),
            ('EL ALTAR', 0, 1, 1),
            ('MATUS', 0, 1, 1),
            ('PUELA', 0, 1, 1),
            ('SAN ANTONIO DE BAYUSHIG', 0, 1, 1),
            ('LA CANDELARIA', 0, 1, 1),
            ('BILBAO (CAB.EN QUILLUYACU)', 0, 1, 1),
            ('CUMANDÁ', 0, 1, 1),
            ('LA PROVIDENCIA', 0, 1, 1),
            ('MACHALA', 0, 1, 1),
            ('PUERTO BOLÍVAR', 0, 1, 1),
            ('NUEVE DE MAYO', 0, 1, 1),
            ('EL CAMBIO', 0, 1, 1),
            ('MACHALA', 0, 1, 1),
            ('EL CAMBIO', 0, 1, 1),
            ('EL RETIRO', 0, 1, 1),
            ('ARENILLAS', 0, 1, 1),
            ('CHACRAS', 0, 1, 1),
            ('LA LIBERTAD', 0, 1, 1),
            ('LAS LAJAS (CAB. EN LA VICTORIA)', 0, 1, 1),
            ('PALMALES', 0, 1, 1),
            ('CARCABÓN', 0, 1, 1),
            ('PACCHA', 0, 1, 1),
            ('AYAPAMBA', 0, 1, 1),
            ('CORDONCILLO', 0, 1, 1),
            ('MILAGRO', 0, 1, 1),
            ('SAN JOSÉ', 0, 1, 1),
            ('SAN JUAN DE CERRO AZUL', 0, 1, 1),
            ('BALSAS', 0, 1, 1),
            ('BELLAMARÍA', 0, 1, 1),
            ('CHILLA', 0, 1, 1),
            ('EL GUABO', 0, 1, 1),
            ('BARBONES (SUCRE)', 0, 1, 1),
            ('LA IBERIA', 0, 1, 1),
            ('TENDALES (CAB.EN PUERTO TENDALES)', 0, 1, 1),
            ('RÍO BONITO', 0, 1, 1),
            ('ECUADOR', 0, 1, 1),
            ('EL PARAÍSO', 0, 1, 1),
            ('HUALTACO', 0, 1, 1),
            ('MILTON REYES', 0, 1, 1),
            ('UNIÓN LOJANA', 0, 1, 1),
            ('HUAQUILLAS', 0, 1, 1),
            ('MARCABELÍ', 0, 1, 1),
            ('EL INGENIO', 0, 1, 1),
            ('BOLÍVAR', 0, 1, 1),
            ('LOMA DE FRANCO', 0, 1, 1),
            ('OCHOA LEÓN (MATRIZ)', 0, 1, 1),
            ('TRES CERRITOS', 0, 1, 1),
            ('PASAJE', 0, 1, 1),
            ('BUENAVISTA', 0, 1, 1),
            ('CASACAY', 0, 1, 1),
            ('LA PEAÑA', 0, 1, 1),
            ('PROGRESO', 0, 1, 1),
            ('UZHCURRUMI', 0, 1, 1),
            ('CAÑAQUEMADA', 0, 1, 1),
            ('LA MATRIZ', 0, 1, 1),
            ('LA SUSAYA', 0, 1, 1),
            ('PIÑAS GRANDE', 0, 1, 1),
            ('PIÑAS', 0, 1, 1),
            ('CAPIRO (CAB. EN LA CAPILLA DE CAPIRO)', 0, 1, 1),
            ('LA BOCANA', 0, 1, 1),
            ('MOROMORO (CAB. EN EL VADO)', 0, 1, 1),
            ('PIEDRAS', 0, 1, 1),
            ('SAN ROQUE (AMBROSIO MALDONADO)', 0, 1, 1),
            ('SARACAY', 0, 1, 1),
            ('PORTOVELO', 0, 1, 1),
            ('CURTINCAPA', 0, 1, 1),
            ('MORALES', 0, 1, 1),
            ('SALATÍ', 0, 1, 1),
            ('SANTA ROSA', 0, 1, 1),
            ('PUERTO JELÍ', 0, 1, 1),
            ('BALNEARIO JAMBELÍ (SATÉLITE)', 0, 1, 1),
            ('JUMÓN (SATÉLITE)', 0, 1, 1),
            ('NUEVO SANTA ROSA', 0, 1, 1),
            ('SANTA ROSA', 0, 1, 1),
            ('BELLAVISTA', 0, 1, 1),
            ('JAMBELÍ', 0, 1, 1),
            ('LA AVANZADA', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('TORATA', 0, 1, 1),
            ('VICTORIA', 0, 1, 1),
            ('BELLAMARÍA', 0, 1, 1),
            ('ZARUMA', 0, 1, 1),
            ('ABAÑÍN', 0, 1, 1),
            ('ARCAPAMBA', 0, 1, 1),
            ('GUANAZÁN', 0, 1, 1),
            ('GUIZHAGUIÑA', 0, 1, 1),
            ('HUERTAS', 0, 1, 1),
            ('MALVAS', 0, 1, 1),
            ('MULUNCAY GRANDE', 0, 1, 1),
            ('SINSAO', 0, 1, 1),
            ('SALVIAS', 0, 1, 1),
            ('LA VICTORIA', 0, 1, 1),
            ('PLATANILLOS', 0, 1, 1),
            ('VALLE HERMOSO', 0, 1, 1),
            ('LA VICTORIA', 0, 1, 1),
            ('LA LIBERTAD', 0, 1, 1),
            ('EL PARAÍSO', 0, 1, 1),
            ('SAN ISIDRO', 0, 1, 1),
            ('BARTOLOMÉ RUIZ (CÉSAR FRANCO CARRIÓN)', 0, 1, 1),
            ('5 DE AGOSTO', 0, 1, 1),
            ('ESMERALDAS', 0, 1, 1),
            ('LUIS TELLO (LAS PALMAS)', 0, 1, 1),
            ('SIMÓN PLATA TORRES', 0, 1, 1),
            ('ESMERALDAS', 0, 1, 1),
            ('ATACAMES', 0, 1, 1),
            ('CAMARONES (CAB. EN SAN VICENTE)', 0, 1, 1),
            ('CRNEL. CARLOS CONCHA TORRES (CAB.EN HUELE)', 0, 1, 1),
            ('CHINCA', 0, 1, 1),
            ('CHONTADURO', 0, 1, 1),
            ('CHUMUNDÉ', 0, 1, 1),
            ('LAGARTO', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('MAJUA', 0, 1, 1),
            ('MONTALVO (CAB. EN HORQUETA)', 0, 1, 1),
            ('RÍO VERDE', 0, 1, 1),
            ('ROCAFUERTE', 0, 1, 1),
            ('SAN MATEO', 0, 1, 1),
            ('SÚA (CAB. EN LA BOCANA)', 0, 1, 1),
            ('TABIAZO', 0, 1, 1),
            ('TACHINA', 0, 1, 1),
            ('TONCHIGÜE', 0, 1, 1),
            ('MUISNE', 0, 1, 1),
            ('BOLÍVAR', 0, 1, 1),
            ('DAULE', 0, 1, 1),
            ('GALERA', 0, 1, 1),
            ('QUINGUE (OLMEDO PERDOMO FRANCO)', 0, 1, 1),
            ('SALIMA', 0, 1, 1),
            ('SAN FRANCISCO', 0, 1, 1),
            ('SAN GREGORIO', 0, 1, 1),
            ('SAN JOSÉ DE CHAMANGA (CAB.EN CHAMANGA)', 0, 1, 1),
            ('ROSA ZÁRATE (QUININDÉ)', 0, 1, 1),
            ('CUBE', 0, 1, 1),
            ('CHURA (CHANCAMA) (CAB. EN EL YERBERO)', 0, 1, 1),
            ('MALIMPIA', 0, 1, 1),
            ('VICHE', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('SAN LORENZO', 0, 1, 1),
            ('ALTO TAMBO (CAB. EN GUADUAL)', 0, 1, 1),
            ('ANCÓN (PICHANGAL) (CAB. EN PALMA REAL)', 0, 1, 1),
            ('CALDERÓN', 0, 1, 1),
            ('CARONDELET', 0, 1, 1),
            ('5 DE JUNIO (CAB. EN UIMBI)', 0, 1, 1),
            ('CONCEPCIÓN', 0, 1, 1),
            ('MATAJE (CAB. EN SANTANDER)', 0, 1, 1),
            ('SAN JAVIER DE CACHAVÍ (CAB. EN SAN JAVIER)', 0, 1, 1),
            ('SANTA RITA', 0, 1, 1),
            ('TAMBILLO', 0, 1, 1),
            ('TULULBÍ (CAB. EN RICAURTE)', 0, 1, 1),
            ('URBINA', 0, 1, 1),
            ('ATACAMES', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('SÚA (CAB. EN LA BOCANA)', 0, 1, 1),
            ('TONCHIGÜE', 0, 1, 1),
            ('TONSUPA', 0, 1, 1),
            ('RIOVERDE', 0, 1, 1),
            ('CHONTADURO', 0, 1, 1),
            ('CHUMUNDÉ', 0, 1, 1),
            ('LAGARTO', 0, 1, 1),
            ('MONTALVO (CAB. EN HORQUETA)', 0, 1, 1),
            ('ROCAFUERTE', 0, 1, 1),
            ('LA CONCORDIA', 0, 1, 1),
            ('MONTERREY', 0, 1, 1),
            ('LA VILLEGAS', 0, 1, 1),
            ('PLAN PILOTO', 0, 1, 1),
            ('AYACUCHO', 0, 1, 1),
            ('BOLÍVAR (SAGRARIO)', 0, 1, 1),
            ('CARBO (CONCEPCIÓN)', 0, 1, 1),
            ('FEBRES CORDERO', 0, 1, 1),
            ('GARCÍA MORENO', 0, 1, 1),
            ('LETAMENDI', 0, 1, 1),
            ('NUEVE DE OCTUBRE', 0, 1, 1),
            ('OLMEDO (SAN ALEJO)', 0, 1, 1),
            ('ROCA', 0, 1, 1),
            ('ROCAFUERTE', 0, 1, 1),
            ('SUCRE', 0, 1, 1),
            ('TARQUI', 0, 1, 1),
            ('URDANETA', 0, 1, 1),
            ('XIMENA', 0, 1, 1),
            ('PASCUALES', 0, 1, 1),
            ('GUAYAQUIL', 0, 1, 1),
            ('CHONGÓN', 0, 1, 1),
            ('JUAN GÓMEZ RENDÓN (PROGRESO)', 0, 1, 1),
            ('MORRO', 0, 1, 1),
            ('PASCUALES', 0, 1, 1),
            ('PLAYAS (GRAL. VILLAMIL)', 0, 1, 1),
            ('POSORJA', 0, 1, 1),
            ('PUNÁ', 0, 1, 1),
            ('TENGUEL', 0, 1, 1),
            ('ALFREDO BAQUERIZO MORENO (JUJÁN) ALFREDO BAQUERIZO MORENO (JUJÁN)', 0, 1, 1),
            ('BALAO BALAO', 0, 1, 1),
            ('BALZAR BALZAR', 0, 1, 1),
            ('COLIMES COLIMES', 0, 1, 1),
            ('COLIMES SAN JACINTO', 0, 1, 1),
            ('DAULE', 0, 1, 1),
            ('LA AURORA (SATÉLITE)', 0, 1, 1),
            ('BANIFE', 0, 1, 1),
            ('EMILIANO CAICEDO MARCOS', 0, 1, 1),
            ('MAGRO', 0, 1, 1),
            ('PADRE JUAN BAUTISTA AGUIRRE', 0, 1, 1),
            ('SANTA CLARA', 0, 1, 1),
            ('VICENTE PIEDRAHITA', 0, 1, 1),
            ('DAULE', 0, 1, 1),
            ('ISIDRO AYORA (SOLEDAD)', 0, 1, 1),
            ('JUAN BAUTISTA AGUIRRE (LOS TINTOS)', 0, 1, 1),
            ('LAUREL', 0, 1, 1),
            ('LIMONAL', 0, 1, 1),
            ('LOMAS DE SARGENTILLO', 0, 1, 1),
            ('LOS LOJAS (ENRIQUE BAQUERIZO MORENO)', 0, 1, 1),
            ('PIEDRAHITA (NOBOL)', 0, 1, 1),
            ('DURÁN ELOY ALFARO (DURÁN)', 0, 1, 1),
            ('DURÁN EL RECREO', 0, 1, 1),
            ('DURÁN ELOY ALFARO (DURÁN)', 0, 1, 1),
            ('EL EMPALME VELASCO IBARRA (EL EMPALME)', 0, 1, 1),
            ('EL EMPALME GUAYAS (PUEBLO NUEVO)', 0, 1, 1),
            ('EL EMPALME EL ROSARIO', 0, 1, 1),
            ('EL TRIUNFO EL TRIUNFO', 0, 1, 1),
            ('MILAGRO MILAGRO', 0, 1, 1),
            ('MILAGRO CHOBO', 0, 1, 1),
            ('MILAGRO GENERAL ELIZALDE (BUCAY)', 0, 1, 1),
            ('MILAGRO MARISCAL SUCRE (HUAQUES)', 0, 1, 1),
            ('MILAGRO ROBERTO ASTUDILLO (CAB. EN CRUCE DE VENECIA)', 0, 1, 1),
            ('NARANJAL NARANJAL', 0, 1, 1),
            ('NARANJAL JESÚS MARÍA', 0, 1, 1),
            ('NARANJAL SAN CARLOS', 0, 1, 1),
            ('NARANJAL SANTA ROSA DE FLANDES', 0, 1, 1),
            ('NARANJAL TAURA', 0, 1, 1),
            ('NARANJITO NARANJITO', 0, 1, 1),
            ('PALESTINA PALESTINA', 0, 1, 1),
            ('PEDRO CARBO PEDRO CARBO', 0, 1, 1),
            ('PEDRO CARBO VALLE DE LA VIRGEN', 0, 1, 1),
            ('PEDRO CARBO SABANILLA', 0, 1, 1),
            ('SAMBORONDÓN SAMBORONDÓN', 0, 1, 1),
            ('SAMBORONDÓN LA PUNTILLA (SATÉLITE)', 0, 1, 1),
            ('SAMBORONDÓN SAMBORONDÓN', 0, 1, 1),
            ('SAMBORONDÓN TARIFA', 0, 1, 1),
            ('SANTA LUCÍA SANTA LUCÍA', 0, 1, 1),
            ('SALITRE (URBINA JADO) BOCANA', 0, 1, 1),
            ('SALITRE (URBINA JADO) CANDILEJOS', 0, 1, 1),
            ('SALITRE (URBINA JADO) CENTRAL', 0, 1, 1),
            ('SALITRE (URBINA JADO) PARAÍSO', 0, 1, 1),
            ('SALITRE (URBINA JADO) SAN MATEO', 0, 1, 1),
            ('SALITRE (URBINA JADO) EL SALITRE (LAS RAMAS)', 0, 1, 1),
            ('SALITRE (URBINA JADO) GRAL. VERNAZA (DOS ESTEROS)', 0, 1, 1),
            ('SALITRE (URBINA JADO) LA VICTORIA (ÑAUZA)', 0, 1, 1),
            ('SALITRE (URBINA JADO) JUNQUILLAL', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI SAN JACINTO DE YAGUACHI', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI CRNEL. LORENZO DE GARAICOA (PEDREGAL)', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI CRNEL. MARCELINO MARIDUEÑA (SAN CARLOS)', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI GRAL. PEDRO J. MONTERO (BOLICHE)', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI SIMÓN BOLÍVAR', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI YAGUACHI VIEJO (CONE)', 0, 1, 1),
            ('SAN JACINTO DE YAGUACHI VIRGEN DE FÁTIMA', 0, 1, 1),
            ('PLAYAS GENERAL VILLAMIL (PLAYAS)', 0, 1, 1),
            ('SIMÓN BOLÍVAR SIMÓN BOLÍVAR', 0, 1, 1),
            ('SIMÓN BOLÍVAR CRNEL.LORENZO DE GARAICOA (PEDREGAL)', 0, 1, 1),
            ('CORONEL MARCELINO MARIDUEÑA CORONEL MARCELINO MARIDUEÑA (SAN CARLOS)', 0, 1, 1),
            ('LOMAS DE SARGENTILLO LOMAS DE SARGENTILLO', 0, 1, 1),
            ('LOMAS DE SARGENTILLO ISIDRO AYORA (SOLEDAD)', 0, 1, 1),
            ('NOBOL NARCISA DE JESÚS', 0, 1, 1),
            ('GENERAL ANTONIO ELIZALDE GENERAL ANTONIO ELIZALDE (BUCAY)', 0, 1, 1),
            ('ISIDRO AYORA ISIDRO AYORA', 0, 1, 1),
            ('CARANQUI', 0, 1, 1),
            ('GUAYAQUIL DE ALPACHACA', 0, 1, 1),
            ('SAGRARIO', 0, 1, 1),
            ('SAN FRANCISCO', 0, 1, 1),
            ('LA DOLOROSA DEL PRIORATO', 0, 1, 1),
            ('SAN MIGUEL DE IBARRA', 0, 1, 1),
            ('AMBUQUÍ', 0, 1, 1),
            ('ANGOCHAGUA', 0, 1, 1),
            ('CAROLINA', 0, 1, 1),
            ('LA ESPERANZA', 0, 1, 1),
            ('LITA', 0, 1, 1),
            ('SALINAS', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('ANDRADE MARÍN (LOURDES)', 0, 1, 1),
            ('ATUNTAQUI', 0, 1, 1),
            ('ATUNTAQUI', 0, 1, 1),
            ('IMBAYA (SAN LUIS DE COBUENDO)', 0, 1, 1),
            ('SAN FRANCISCO DE NATABUELA', 0, 1, 1),
            ('SAN JOSÉ DE CHALTURA', 0, 1, 1),
            ('SAN ROQUE', 0, 1, 1),
            ('SAGRARIO', 0, 1, 1),
            ('SAN FRANCISCO', 0, 1, 1),
            ('COTACACHI', 0, 1, 1),
            ('APUELA', 0, 1, 1),
            ('GARCÍA MORENO (LLURIMAGUA)', 0, 1, 1),
            ('IMANTAG', 0, 1, 1),
            ('PEÑAHERRERA', 0, 1, 1),
            ('PLAZA GUTIÉRREZ (CALVARIO)', 0, 1, 1),
            ('QUIROGA', 0, 1, 1),
            ('6 DE JULIO DE CUELLAJE (CAB. EN CUELLAJE)', 0, 1, 1),
            ('VACAS GALINDO (EL CHURO) (CAB.EN SAN MIGUEL ALTO', 0, 1, 1),
            ('JORDÁN', 0, 1, 1),
            ('SAN LUIS', 0, 1, 1),
            ('OTAVALO', 0, 1, 1),
            ('DR. MIGUEL EGAS CABEZAS (PEGUCHE)', 0, 1, 1),
            ('EUGENIO ESPEJO (CALPAQUÍ)', 0, 1, 1),
            ('GONZÁLEZ SUÁREZ', 0, 1, 1),
            ('PATAQUÍ', 0, 1, 1),
            ('SAN JOSÉ DE QUICHINCHE', 0, 1, 1),
            ('SAN JUAN DE ILUMÁN', 0, 1, 1),
            ('SAN PABLO', 0, 1, 1),
            ('SAN RAFAEL', 0, 1, 1),
            ('SELVA ALEGRE (CAB.EN SAN MIGUEL DE PAMPLONA)', 0, 1, 1),
            ('PIMAMPIRO', 0, 1, 1),
            ('CHUGÁ', 0, 1, 1),
            ('MARIANO ACOSTA', 0, 1, 1),
            ('SAN FRANCISCO DE SIGSIPAMBA', 0, 1, 1),
            ('URCUQUÍ CABECERA CANTONAL', 0, 1, 1),
            ('CAHUASQUÍ', 0, 1, 1),
            ('LA MERCED DE BUENOS AIRES', 0, 1, 1),
            ('PABLO ARENAS', 0, 1, 1),
            ('SAN BLAS', 0, 1, 1),
            ('TUMBABIRO', 0, 1, 1),
            ('EL SAGRARIO', 0, 1, 1),
            ('SAN SEBASTIÁN', 0, 1, 1),
            ('SUCRE', 0, 1, 1),
            ('VALLE', 0, 1, 1),
            ('LOJA', 0, 1, 1),
            ('CHANTACO', 0, 1, 1),
            ('CHUQUIRIBAMBA', 0, 1, 1),
            ('EL CISNE', 0, 1, 1),
            ('GUALEL', 0, 1, 1),
            ('JIMBILLA', 0, 1, 1),
            ('MALACATOS (VALLADOLID)', 0, 1, 1),
            ('SAN LUCAS', 0, 1, 1),
            ('SAN PEDRO DE VILCABAMBA', 0, 1, 1),
            ('SANTIAGO', 0, 1, 1),
            ('TAQUIL (MIGUEL RIOFRÍO)', 0, 1, 1),
            ('VILCABAMBA (VICTORIA)', 0, 1, 1),
            ('YANGANA (ARSENIO CASTILLO)', 0, 1, 1),
            ('QUINARA', 0, 1, 1),
            ('CARIAMANGA', 0, 1, 1),
            ('CHILE', 0, 1, 1),
            ('SAN VICENTE', 0, 1, 1),
            ('CARIAMANGA', 0, 1, 1),
            ('COLAISACA', 0, 1, 1),
            ('EL LUCERO', 0, 1, 1),
            ('UTUANA', 0, 1, 1),
            ('SANGUILLÍN', 0, 1, 1),
            ('CATAMAYO', 0, 1, 1),
            ('SAN JOSÉ', 0, 1, 1),
            ('CATAMAYO (LA TOMA)', 0, 1, 1),
            ('EL TAMBO', 0, 1, 1),
            ('GUAYQUICHUMA', 0, 1, 1),
            ('SAN PEDRO DE LA BENDITA', 0, 1, 1),
            ('ZAMBI', 0, 1, 1),
            ('CELICA', 0, 1, 1),
            ('CRUZPAMBA (CAB. EN CARLOS BUSTAMANTE)', 0, 1, 1),
            ('CHAQUINAL', 0, 1, 1),
            ('12 DE DICIEMBRE (CAB. EN ACHIOTES)', 0, 1, 1),
            ('PINDAL (FEDERICO PÁEZ)', 0, 1, 1),
            ('POZUL (SAN JUAN DE POZUL)', 0, 1, 1),
            ('SABANILLA', 0, 1, 1),
            ('TNTE. MAXIMILIANO RODRÍGUEZ LOAIZA', 0, 1, 1),
            ('CHAGUARPAMBA', 0, 1, 1),
            ('BUENAVISTA', 0, 1, 1),
            ('EL ROSARIO', 0, 1, 1),
            ('SANTA RUFINA', 0, 1, 1),
            ('AMARILLOS', 0, 1, 1),
            ('AMALUZA', 0, 1, 1),
            ('BELLAVISTA', 0, 1, 1),
            ('JIMBURA', 0, 1, 1),
            ('SANTA TERESITA', 0, 1, 1),
            ('27 DE ABRIL (CAB. EN LA NARANJA)', 0, 1, 1),
            ('EL INGENIO', 0, 1, 1),
            ('EL AIRO', 0, 1, 1),
            ('GONZANAMÁ', 0, 1, 1),
            ('CHANGAIMINA (LA LIBERTAD)', 0, 1, 1),
            ('FUNDOCHAMBA', 0, 1, 1),
            ('NAMBACOLA', 0, 1, 1),
            ('PURUNUMA', 0, 1, 1),
            ('QUILANGA ', 0, 1, 1),
            ('SACAPALCA', 0, 1, 1),
            ('SAN ANTONIO DE LAS ARADAS (CAB. EN LAS ARADAS)', 0, 1, 1),
            ('GENERAL ELOY ALFARO (SAN SEBASTIÁN)', 0, 1, 1),
            ('MACARÁ', 0, 1, 1),
            ('MACARÁ', 0, 1, 1),
            ('LARAMA', 0, 1, 1),
            ('LA VICTORIA', 0, 1, 1),
            ('SABIANGO ', 0, 1, 1),
            ('CATACOCHA', 0, 1, 1),
            ('LOURDES', 0, 1, 1),
            ('CATACOCHA', 0, 1, 1),
            ('CANGONAMÁ', 0, 1, 1),
            ('GUACHANAMÁ', 0, 1, 1),
            ('LA TINGUE', 0, 1, 1),
            ('LAURO GUERRERO', 0, 1, 1),
            ('OLMEDO ', 0, 1, 1),
            ('ORIANGA', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('CASANGA', 0, 1, 1),
            ('YAMANA', 0, 1, 1),
            ('ALAMOR', 0, 1, 1),
            ('CIANO', 0, 1, 1),
            ('EL ARENAL', 0, 1, 1),
            ('EL LIMO', 0, 1, 1),
            ('MERCADILLO', 0, 1, 1),
            ('VICENTINO', 0, 1, 1),
            ('SARAGURO', 0, 1, 1),
            ('EL PARAÍSO DE CELÉN', 0, 1, 1),
            ('EL TABLÓN', 0, 1, 1),
            ('LLUZHAPA', 0, 1, 1),
            ('MANÚ', 0, 1, 1),
            ('SAN ANTONIO DE QUMBE', 0, 1, 1),
            ('SAN PABLO DE TENTA', 0, 1, 1),
            ('SAN SEBASTIÁN DE YÚLUC', 0, 1, 1),
            ('SELVA ALEGRE', 0, 1, 1),
            ('URDANETA', 0, 1, 1),
            ('SUMAYPAMBA', 0, 1, 1),
            ('SOZORANGA', 0, 1, 1),
            ('NUEVA FÁTIMA', 0, 1, 1),
            ('TACAMOROS', 0, 1, 1),
            ('ZAPOTILLO', 0, 1, 1),
            ('MANGAHURCO ', 0, 1, 1),
            ('GARZAREAL', 0, 1, 1),
            ('LIMONES', 0, 1, 1),
            ('PALETILLAS', 0, 1, 1),
            ('BOLASPAMBA', 0, 1, 1),
            ('PINDAL', 0, 1, 1),
            ('CHAQUINAL', 0, 1, 1),
            ('12 DE DICIEMBRE', 0, 1, 1),
            ('MILAGROS', 0, 1, 1),
            ('QUILANGA', 0, 1, 1),
            ('FUNDOCHAMBA', 0, 1, 1),
            ('SAN ANTONIO DE LAS ARADAS', 0, 1, 1),
            ('OLMEDO', 0, 1, 1),
            ('LA TINGUE', 0, 1, 1),
            ('CLEMENTE BAQUERIZO', 0, 1, 1),
            ('DR. CAMILO PONCE', 0, 1, 1),
            ('BARREIRO', 0, 1, 1),
            ('EL SALTO', 0, 1, 1),
            ('BABAHOYO', 0, 1, 1),
            ('BARREIRO', 0, 1, 1),
            ('CARACOL', 0, 1, 1),
            ('FEBRES CORDERO', 0, 1, 1),
            ('PIMOCHA', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('BABA', 0, 1, 1),
            ('GUARE', 0, 1, 1),
            ('ISLA DE BEJUCAL', 0, 1, 1),
            ('MONTALVO', 0, 1, 1),
            ('PUEBLOVIEJO', 0, 1, 1),
            ('PUERTO PECHICHE', 0, 1, 1),
            ('SAN JUAN', 0, 1, 1),
            ('QUEVEDO', 0, 1, 1),
            ('SAN CAMILO', 0, 1, 1),
            ('SAN JOSÉ', 0, 1, 1),
            ('GUAYACÁN', 0, 1, 1),
            ('NICOLÁS INFANTE DÍAZ', 0, 1, 1),
            ('SAN CRISTÓBAL', 0, 1, 1),
            ('SIETE DE OCTUBRE', 0, 1, 1),
            ('24 DE MAYO', 0, 1, 1),
            ('VENUS DEL RÍO QUEVEDO', 0, 1, 1),
            ('VIVA ALFARO', 0, 1, 1),
            ('QUEVEDO', 0, 1, 1),
            ('BUENA FÉ', 0, 1, 1),
            ('MOCACHE', 0, 1, 1),
            ('SAN CARLOS', 0, 1, 1),
            ('VALENCIA', 0, 1, 1),
            ('LA ESPERANZA', 0, 1, 1),
            ('CATARAMA', 0, 1, 1),
            ('RICAURTE', 0, 1, 1),
            ('10 DE NOVIEMBRE', 0, 1, 1),
            ('VENTANAS', 0, 1, 1),
            ('QUINSALOMA', 0, 1, 1),
            ('ZAPOTAL', 0, 1, 1),
            ('CHACARITA', 0, 1, 1),
            ('LOS ÁNGELES', 0, 1, 1),
            ('VINCES', 0, 1, 1),
            ('ANTONIO SOTOMAYOR', 0, 1, 1),
            ('PALENQUE', 0, 1, 1),
            ('PALENQUE', 0, 1, 1),
            ('SAN JACINTO DE BUENA FÉ', 0, 1, 1),
            ('7 DE AGOSTO', 0, 1, 1),
            ('11 DE OCTUBRE', 0, 1, 1),
            ('SAN JACINTO DE BUENA FÉ', 0, 1, 1),
            ('PATRICIA PILAR', 0, 1, 1),
            ('VALENCIA VALENCIA', 0, 1, 1),
            ('MOCACHE MOCACHE', 0, 1, 1),
            ('QUINSALOMA QUINSALOMA', 0, 1, 1),
            ('12 DE MARZO', 0, 1, 1),
            ('COLÓN', 0, 1, 1),
            ('PICOAZÁ', 0, 1, 1),
            ('SAN PABLO', 0, 1, 1),
            ('ANDRÉS DE VERA', 0, 1, 1),
            ('FRANCISCO PACHECO', 0, 1, 1),
            ('18 DE OCTUBRE', 0, 1, 1),
            ('SIMÓN BOLÍVAR', 0, 1, 1),
            ('PORTOVIEJO', 0, 1, 1),
            ('ABDÓN CALDERÓN', 0, 1, 1),
            ('ALHAJUELA', 0, 1, 1),
            ('CRUCITA', 0, 1, 1),
            ('PUEBLO NUEVO', 0, 1, 1),
            ('RIOCHICO', 0, 1, 1),
            ('SAN PLÁCIDO', 0, 1, 1),
            ('CHIRIJOS', 0, 1, 1),
            ('CALCETA', 0, 1, 1),
            ('MEMBRILLO', 0, 1, 1),
            ('QUIROGA', 0, 1, 1),
            ('CHONE', 0, 1, 1),
            ('SANTA RITA', 0, 1, 1),
            ('BOYACÁ', 0, 1, 1),
            ('CANUTO', 0, 1, 1),
            ('CONVENTO', 0, 1, 1),
            ('CHIBUNGA', 0, 1, 1),
            ('ELOY ALFARO', 0, 1, 1),
            ('RICAURTE', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('EL CARMEN', 0, 1, 1),
            ('4 DE DICIEMBRE', 0, 1, 1),
            ('EL CARMEN', 0, 1, 1),
            ('WILFRIDO LOOR MOREIRA (MAICITO)', 0, 1, 1),
            ('SAN PEDRO DE SUMA', 0, 1, 1),
            ('FLAVIO ALFARO', 0, 1, 1),
            ('SAN FRANCISCO DE NOVILLO (CAB. EN', 0, 1, 1),
            ('ZAPALLO', 0, 1, 1),
            ('DR. MIGUEL MORÁN LUCIO', 0, 1, 1),
            ('MANUEL INOCENCIO PARRALES Y GUALE', 0, 1, 1),
            ('SAN LORENZO DE JIPIJAPA', 0, 1, 1),
            ('JIPIJAPA', 0, 1, 1),
            ('AMÉRICA', 0, 1, 1),
            ('EL ANEGADO ', 0, 1, 1),
            ('JULCUY', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('MACHALILLA', 0, 1, 1),
            ('MEMBRILLAL', 0, 1, 1),
            ('PEDRO PABLO GÓMEZ', 0, 1, 1),
            ('PUERTO DE CAYO', 0, 1, 1),
            ('PUERTO LÓPEZ', 0, 1, 1),
            ('JUNÍN', 0, 1, 1),
            ('LOS ESTEROS', 0, 1, 1),
            ('MANTA', 0, 1, 1),
            ('SAN MATEO', 0, 1, 1),
            ('TARQUI', 0, 1, 1),
            ('ELOY ALFARO', 0, 1, 1),
            ('MANTA', 0, 1, 1),
            ('SAN LORENZO', 0, 1, 1),
            ('SANTA MARIANITA', 0, 1, 1),
            ('ANIBAL SAN ANDRÉS', 0, 1, 1),
            ('MONTECRISTI', 0, 1, 1),
            ('EL COLORADO', 0, 1, 1),
            ('GENERAL ELOY ALFARO', 0, 1, 1),
            ('LEONIDAS PROAÑO', 0, 1, 1),
            ('MONTECRISTI', 0, 1, 1),
            ('JARAMIJÓ', 0, 1, 1),
            ('LA PILA', 0, 1, 1),
            ('PAJÁN', 0, 1, 1),
            ('CAMPOZANO (LA PALMA DE PAJÁN)', 0, 1, 1),
            ('CASCOL', 0, 1, 1),
            ('GUALE', 0, 1, 1),
            ('LASCANO', 0, 1, 1),
            ('PICHINCHA', 0, 1, 1),
            ('BARRAGANETE', 0, 1, 1),
            ('SAN SEBASTIÁN', 0, 1, 1),
            ('ROCAFUERTE', 0, 1, 1),
            ('SANTA ANA', 0, 1, 1),
            ('LODANA', 0, 1, 1),
            ('SANTA ANA DE VUELTA LARGA', 0, 1, 1),
            ('AYACUCHO', 0, 1, 1),
            ('HONORATO VÁSQUEZ', 0, 1, 1),
            ('LA UNIÓN', 0, 1, 1),
            ('OLMEDO', 0, 1, 1),
            ('SAN PABLO', 0, 1, 1),
            ('BAHÍA DE CARÁQUEZ', 0, 1, 1),
            ('LEONIDAS PLAZA GUTIÉRREZ', 0, 1, 1),
            ('BAHÍA DE CARÁQUEZ', 0, 1, 1),
            ('CANOA', 0, 1, 1),
            ('COJIMÍES', 0, 1, 1),
            ('CHARAPOTÓ', 0, 1, 1),
            ('10 DE AGOSTO', 0, 1, 1),
            ('JAMA', 0, 1, 1),
            ('PEDERNALES', 0, 1, 1),
            ('SAN ISIDRO', 0, 1, 1),
            ('SAN VICENTE', 0, 1, 1),
            ('TOSAGUA', 0, 1, 1),
            ('BACHILLERO', 0, 1, 1),
            ('ANGEL PEDRO GILER (LA ESTANCILLA)', 0, 1, 1),
            ('SUCRE', 0, 1, 1),
            ('BELLAVISTA', 0, 1, 1),
            ('NOBOA', 0, 1, 1),
            ('ARQ. SIXTO DURÁN BALLÉN', 0, 1, 1),
            ('PEDERNALES', 0, 1, 1),
            ('COJIMÍES', 0, 1, 1),
            ('10 DE AGOSTO', 0, 1, 1),
            ('ATAHUALPA', 0, 1, 1),
            ('OLMEDO', 0, 1, 1),
            ('PUERTO LÓPEZ', 0, 1, 1),
            ('MACHALILLA', 0, 1, 1),
            ('SALANGO', 0, 1, 1),
            ('JAMAJARAMIJÓ', 0, 1, 1),
            ('SAN VICENTE', 0, 1, 1),
            ('CANOA', 0, 1, 1),
            ('MACAS', 0, 1, 1),
            ('ALSHI', 0, 1, 1),
            ('CHIGUAZA', 0, 1, 1),
            ('GENERAL PROAÑO', 0, 1, 1),
            ('HUASAGA', 0, 1, 1),
            ('MACUMA', 0, 1, 1),
            ('SAN ISIDRO', 0, 1, 1),
            ('SEVILLA DON BOSCO', 0, 1, 1),
            ('SINAÍ', 0, 1, 1),
            ('TAISHA', 0, 1, 1),
            ('ZUÑA (ZÚÑAC)', 0, 1, 1),
            ('TUUTINENTZA', 0, 1, 1),
            ('CUCHAENTZA', 0, 1, 1),
            ('SAN JOSÉ DE MORONA', 0, 1, 1),
            ('RÍO BLANCO', 0, 1, 1),
            ('GUALAQUIZA', 0, 1, 1),
            ('MERCEDES MOLINA', 0, 1, 1),
            ('GUALAQUIZA', 0, 1, 1),
            ('AMAZONAS (ROSARIO DE CUYES)', 0, 1, 1),
            ('BERMEJOS', 0, 1, 1),
            ('BOMBOIZA', 0, 1, 1),
            ('CHIGÜINDA', 0, 1, 1),
            ('EL ROSARIO', 0, 1, 1),
            ('NUEVA TARQUI', 0, 1, 1),
            ('SAN MIGUEL DE CUYES', 0, 1, 1),
            ('EL IDEAL', 0, 1, 1),
            ('GENERAL LEONIDAS PLAZA GUTIÉRREZ (LIMÓN)', 0, 1, 1),
            ('INDANZA', 0, 1, 1),
            ('PAN DE AZÚCAR', 0, 1, 1),
            ('SAN ANTONIO (CAB. EN SAN ANTONIO CENTRO', 0, 1, 1),
            ('SAN CARLOS DE LIMÓN (SAN CARLOS DEL', 0, 1, 1),
            ('SAN JUAN BOSCO', 0, 1, 1),
            ('SAN MIGUEL DE CONCHAY', 0, 1, 1),
            ('SANTA SUSANA DE CHIVIAZA (CAB. EN CHIVIAZA)', 0, 1, 1),
            ('YUNGANZA (CAB. EN EL ROSARIO)', 0, 1, 1),
            ('PALORA (METZERA)', 0, 1, 1),
            ('ARAPICOS', 0, 1, 1),
            ('CUMANDÁ (CAB. EN COLONIA AGRÍCOLA SEVILLA DEL ORO)', 0, 1, 1),
            ('HUAMBOYA', 0, 1, 1),
            ('SANGAY (CAB. EN NAYAMANACA)', 0, 1, 1),
            ('SANTIAGO DE MÉNDEZ', 0, 1, 1),
            ('COPAL', 0, 1, 1),
            ('CHUPIANZA', 0, 1, 1),
            ('PATUCA', 0, 1, 1),
            ('SAN LUIS DE EL ACHO (CAB. EN EL ACHO)', 0, 1, 1),
            ('SANTIAGO', 0, 1, 1),
            ('TAYUZA', 0, 1, 1),
            ('SAN FRANCISCO DE CHINIMBIMI', 0, 1, 1),
            ('SUCÚA', 0, 1, 1),
            ('ASUNCIÓN', 0, 1, 1),
            ('HUAMBI', 0, 1, 1),
            ('LOGROÑO', 0, 1, 1),
            ('YAUPI', 0, 1, 1),
            ('SANTA MARIANITA DE JESÚS', 0, 1, 1),
            ('HUAMBOYA', 0, 1, 1),
            ('CHIGUAZA', 0, 1, 1),
            ('PABLO SEXTO', 0, 1, 1),
            ('SAN JUAN BOSCO', 0, 1, 1),
            ('PAN DE AZÚCAR', 0, 1, 1),
            ('SAN CARLOS DE LIMÓN', 0, 1, 1),
            ('SAN JACINTO DE WAKAMBEIS', 0, 1, 1),
            ('SANTIAGO DE PANANZA', 0, 1, 1),
            ('TAISHA', 0, 1, 1),
            ('HUASAGA (CAB. EN WAMPUIK)', 0, 1, 1),
            ('MACUMA', 0, 1, 1),
            ('TUUTINENTZA', 0, 1, 1),
            ('PUMPUENTSA', 0, 1, 1),
            ('LOGROÑO', 0, 1, 1),
            ('YAUPI', 0, 1, 1),
            ('SHIMPIS', 0, 1, 1),
            ('PABLO SEXTO PABLO SEXTO', 0, 1, 1),
            ('TIWINTZA SANTIAGO', 0, 1, 1),
            ('TIWINTZA SAN JOSÉ DE MORONA', 0, 1, 1),
            ('TENA', 0, 1, 1),
            ('AHUANO', 0, 1, 1),
            ('CARLOS JULIO AROSEMENA TOLA (ZATZA-YACU)', 0, 1, 1),
            ('CHONTAPUNTA', 0, 1, 1),
            ('PANO', 0, 1, 1),
            ('PUERTO MISAHUALLI', 0, 1, 1),
            ('PUERTO NAPO', 0, 1, 1),
            ('TÁLAG', 0, 1, 1),
            ('SAN JUAN DE MUYUNA', 0, 1, 1),
            ('ARCHIDONA', 0, 1, 1),
            ('AVILA', 0, 1, 1),
            ('COTUNDO', 0, 1, 1),
            ('LORETO', 0, 1, 1),
            ('SAN PABLO DE USHPAYACU', 0, 1, 1),
            ('PUERTO MURIALDO', 0, 1, 1),
            ('EL CHACO', 0, 1, 1),
            ('LINARES', 0, 1, 1),
            ('OYACACHI', 0, 1, 1),
            ('SANTA ROSA', 0, 1, 1),
            ('SARDINAS', 0, 1, 1),
            ('BAEZA', 0, 1, 1),
            ('COSANGA', 0, 1, 1),
            ('CUYUJA', 0, 1, 1),
            ('PAPALLACTA', 0, 1, 1),
            ('SAN FRANCISCO DE BORJA (VIRGILIO DÁVILA)', 0, 1, 1),
            ('SAN JOSÉ DEL PAYAMINO', 0, 1, 1),
            ('SUMACO', 0, 1, 1),
            ('NAPO CARLOS JULIO AROSEMENA TOLA CARLOS JULIO AROSEMENA TOLA', 0, 1, 1),
            ('PUYO', 0, 1, 1),
            ('ARAJUNO', 0, 1, 1),
            ('CANELOS', 0, 1, 1),
            ('CURARAY', 0, 1, 1),
            ('DIEZ DE AGOSTO', 0, 1, 1),
            ('FÁTIMA', 0, 1, 1),
            ('MONTALVO (ANDOAS)', 0, 1, 1),
            ('POMONA', 0, 1, 1),
            ('RÍO CORRIENTES', 0, 1, 1),
            ('RÍO TIGRE', 0, 1, 1),
            ('SANTA CLARA', 0, 1, 1),
            ('SARAYACU', 0, 1, 1),
            ('SIMÓN BOLÍVAR (CAB. EN MUSHULLACTA)', 0, 1, 1),
            ('TARQUI', 0, 1, 1),
            ('TENIENTE HUGO ORTIZ', 0, 1, 1),
            ('VERACRUZ (INDILLAMA) (CAB. EN INDILLAMA)', 0, 1, 1),
            ('EL TRIUNFO', 0, 1, 1),
            ('MERA MERA', 0, 1, 1),
            ('MERA MADRE TIERRA', 0, 1, 1),
            ('MERA SHELL', 0, 1, 1),
            ('SANTA CLARA SANTA CLARA', 0, 1, 1),
            ('SANTA CLARA SAN JOSÉ', 0, 1, 1),
            ('ARAJUNO ARAJUNO', 0, 1, 1),
            ('ARAJUNO CURARAY', 0, 1, 1),
            ('BELISARIO QUEVEDO', 0, 1, 1),
            ('CARCELÉN', 0, 1, 1),
            ('CENTRO HISTÓRICO', 0, 1, 1),
            ('COCHAPAMBA', 0, 1, 1),
            ('COMITÉ DEL PUEBLO', 0, 1, 1),
            ('CHILIBULO', 0, 1, 1),
            ('CHILLOGALLO', 0, 1, 1),
            ('CHIMBACALLE', 0, 1, 1),
            ('GUAMANÍ', 0, 1, 1),
            ('IÑAQUITO', 0, 1, 1),
            ('ITCHIMBÍA', 0, 1, 1),
            ('JIPIJAPA', 0, 1, 1),
            ('KENNEDY', 0, 1, 1),
            ('LA ARGELIA', 0, 1, 1),
            ('LA CONCEPCIÓN', 0, 1, 1),
            ('LA ECUATORIANA', 0, 1, 1),
            ('LA FERROVIARIA', 0, 1, 1),
            ('LA LIBERTAD', 0, 1, 1),
            ('LA MAGDALENA', 0, 1, 1),
            ('LA MENA', 0, 1, 1),
            ('MARISCAL SUCRE', 0, 1, 1),
            ('PONCEANO', 0, 1, 1),
            ('PUENGASÍ', 0, 1, 1),
            ('QUITUMBE', 0, 1, 1),
            ('RUMIPAMBA', 0, 1, 1),
            ('SAN BARTOLO', 0, 1, 1),
            ('SAN ISIDRO DEL INCA', 0, 1, 1),
            ('SAN JUAN', 0, 1, 1),
            ('SOLANDA', 0, 1, 1),
            ('TURUBAMBA', 0, 1, 1),
            ('QUITO DISTRITO METROPOLITANO', 0, 1, 1),
            ('ALANGASÍ', 0, 1, 1),
            ('AMAGUAÑA', 0, 1, 1),
            ('ATAHUALPA', 0, 1, 1),
            ('CALACALÍ', 0, 1, 1),
            ('CALDERÓN', 0, 1, 1),
            ('CONOCOTO', 0, 1, 1),
            ('CUMBAYÁ', 0, 1, 1),
            ('CHAVEZPAMBA', 0, 1, 1),
            ('CHECA', 0, 1, 1),
            ('EL QUINCHE', 0, 1, 1),
            ('GUALEA', 0, 1, 1),
            ('GUANGOPOLO', 0, 1, 1),
            ('GUAYLLABAMBA', 0, 1, 1),
            ('LA MERCED', 0, 1, 1),
            ('LLANO CHICO', 0, 1, 1),
            ('LLOA', 0, 1, 1),
            ('MINDO', 0, 1, 1),
            ('NANEGAL', 0, 1, 1),
            ('NANEGALITO', 0, 1, 1),
            ('NAYÓN', 0, 1, 1),
            ('NONO', 0, 1, 1),
            ('PACTO', 0, 1, 1),
            ('PEDRO VICENTE MALDONADO', 0, 1, 1),
            ('PERUCHO', 0, 1, 1),
            ('PIFO', 0, 1, 1),
            ('PÍNTAG', 0, 1, 1),
            ('POMASQUI', 0, 1, 1),
            ('PUÉLLARO', 0, 1, 1),
            ('PUEMBO', 0, 1, 1),
            ('SAN ANTONIO', 0, 1, 1),
            ('SAN JOSÉ DE MINAS', 0, 1, 1),
            ('SAN MIGUEL DE LOS BANCOS', 0, 1, 1),
            ('TABABELA', 0, 1, 1),
            ('TUMBACO', 0, 1, 1),
            ('YARUQUÍ', 0, 1, 1),
            ('ZAMBIZA', 0, 1, 1),
            ('PUERTO QUITO', 0, 1, 1),
            ('AYORA', 0, 1, 1),
            ('CAYAMBE', 0, 1, 1),
            ('JUAN MONTALVO', 0, 1, 1),
            ('CAYAMBE', 0, 1, 1),
            ('ASCÁZUBI', 0, 1, 1),
            ('CANGAHUA', 0, 1, 1),
            ('OLMEDO (PESILLO)', 0, 1, 1),
            ('OTÓN', 0, 1, 1),
            ('SANTA ROSA DE CUZUBAMBA', 0, 1, 1),
            ('MACHACHI', 0, 1, 1),
            ('ALÓAG', 0, 1, 1),
            ('ALOASÍ', 0, 1, 1),
            ('CUTUGLAHUA', 0, 1, 1),
            ('EL CHAUPI', 0, 1, 1),
            ('MANUEL CORNEJO ASTORGA (TANDAPI)', 0, 1, 1),
            ('TAMBILLO', 0, 1, 1),
            ('UYUMBICHO', 0, 1, 1),
            ('TABACUNDO', 0, 1, 1),
            ('LA ESPERANZA', 0, 1, 1),
            ('MALCHINGUÍ', 0, 1, 1),
            ('TOCACHI', 0, 1, 1),
            ('TUPIGACHI', 0, 1, 1),
            ('SANGOLQUÍ', 0, 1, 1),
            ('SAN PEDRO DE TABOADA', 0, 1, 1),
            ('SAN RAFAEL', 0, 1, 1),
            ('SANGOLQUI', 0, 1, 1),
            ('COTOGCHOA', 0, 1, 1),
            ('RUMIPAMBA', 0, 1, 1),
            ('SAN MIGUEL DE LOS BANCOS', 0, 1, 1),
            ('MINDO', 0, 1, 1),
            ('PEDRO VICENTE MALDONADO', 0, 1, 1),
            ('PUERTO QUITO', 0, 1, 1),
            ('PEDRO VICENTE MALDONADO', 0, 1, 1),
            ('QUITO PUERTO QUITO', 0, 1, 1),
            ('ATOCHA – FICOA', 0, 1, 1),
            ('CELIANO MONGE', 0, 1, 1),
            ('HUACHI CHICO', 0, 1, 1),
            ('HUACHI LORETO', 0, 1, 1),
            ('LA MERCED', 0, 1, 1),
            ('LA PENÍNSULA', 0, 1, 1),
            ('MATRIZ', 0, 1, 1),
            ('PISHILATA', 0, 1, 1),
            ('SAN FRANCISCO', 0, 1, 1),
            ('AMBATO', 0, 1, 1),
            ('AMBATILLO', 0, 1, 1),
            ('ATAHUALPA (CHISALATA)', 0, 1, 1),
            ('AUGUSTO N. MARTÍNEZ (MUNDUGLEO)', 0, 1, 1),
            ('CONSTANTINO FERNÁNDEZ (CAB. EN CULLITAHUA)', 0, 1, 1),
            ('HUACHI GRANDE', 0, 1, 1),
            ('IZAMBA', 0, 1, 1),
            ('JUAN BENIGNO VELA', 0, 1, 1),
            ('MONTALVO', 0, 1, 1),
            ('PASA', 0, 1, 1),
            ('PICAIGUA', 0, 1, 1),
            ('PILAGÜÍN (PILAHÜÍN)', 0, 1, 1),
            ('QUISAPINCHA (QUIZAPINCHA)', 0, 1, 1),
            ('SAN BARTOLOMÉ DE PINLLOG', 0, 1, 1),
            ('SAN FERNANDO (PASA SAN FERNANDO)', 0, 1, 1),
            ('SANTA ROSA', 0, 1, 1),
            ('TOTORAS', 0, 1, 1),
            ('CUNCHIBAMBA', 0, 1, 1),
            ('UNAMUNCHO', 0, 1, 1),
            ('BAÑOS DE AGUA SANTA', 0, 1, 1),
            ('LLIGUA', 0, 1, 1),
            ('RÍO NEGRO', 0, 1, 1),
            ('RÍO VERDE', 0, 1, 1),
            ('ULBA', 0, 1, 1),
            ('CEVALLOS', 0, 1, 1),
            ('MOCHA', 0, 1, 1),
            ('PINGUILÍ', 0, 1, 1),
            ('PATATE', 0, 1, 1),
            ('EL TRIUNFO', 0, 1, 1),
            ('LOS ANDES (CAB. EN POATUG)', 0, 1, 1),
            ('SUCRE (CAB. EN SUCRE-PATATE URCU)', 0, 1, 1),
            ('QUERO', 0, 1, 1),
            ('RUMIPAMBA', 0, 1, 1),
            ('YANAYACU - MOCHAPATA (CAB. EN YANAYACU)', 0, 1, 1),
            ('PELILEO', 0, 1, 1),
            ('PELILEO GRANDE', 0, 1, 1),
            ('PELILEO', 0, 1, 1),
            ('BENÍTEZ (PACHANLICA)', 0, 1, 1),
            ('BOLÍVAR', 0, 1, 1),
            ('COTALÓ', 0, 1, 1),
            ('CHIQUICHA (CAB. EN CHIQUICHA GRANDE)', 0, 1, 1),
            ('EL ROSARIO (RUMICHACA)', 0, 1, 1),
            ('GARCÍA MORENO (CHUMAQUI)', 0, 1, 1),
            ('GUAMBALÓ (HUAMBALÓ)', 0, 1, 1),
            ('SALASACA', 0, 1, 1),
            ('CIUDAD NUEVA', 0, 1, 1),
            ('PÍLLARO', 0, 1, 1),
            ('PÍLLARO', 0, 1, 1),
            ('BAQUERIZO MORENO', 0, 1, 1),
            ('EMILIO MARÍA TERÁN (RUMIPAMBA)', 0, 1, 1),
            ('MARCOS ESPINEL (CHACATA)', 0, 1, 1),
            ('PRESIDENTE URBINA (CHAGRAPAMBA -PATZUCUL)', 0, 1, 1),
            ('SAN ANDRÉS', 0, 1, 1),
            ('SAN JOSÉ DE POALÓ', 0, 1, 1),
            ('SAN MIGUELITO', 0, 1, 1),
            ('TISALEO', 0, 1, 1),
            ('QUINCHICOTO', 0, 1, 1),
            ('EL LIMÓN', 0, 1, 1),
            ('ZAMORA', 0, 1, 1),
            ('ZAMORA', 0, 1, 1),
            ('CUMBARATZA', 0, 1, 1),
            ('GUADALUPE', 0, 1, 1),
            ('IMBANA (LA VICTORIA DE IMBANA)', 0, 1, 1),
            ('PAQUISHA', 0, 1, 1),
            ('SABANILLA', 0, 1, 1),
            ('TIMBARA', 0, 1, 1),
            ('ZUMBI', 0, 1, 1),
            ('SAN CARLOS DE LAS MINAS', 0, 1, 1),
            ('ZUMBA', 0, 1, 1),
            ('CHITO', 0, 1, 1),
            ('EL CHORRO', 0, 1, 1),
            ('EL PORVENIR DEL CARMEN', 0, 1, 1),
            ('LA CHONTA', 0, 1, 1),
            ('PALANDA', 0, 1, 1),
            ('PUCAPAMBA', 0, 1, 1),
            ('SAN FRANCISCO DEL VERGEL', 0, 1, 1),
            ('VALLADOLID', 0, 1, 1),
            ('SAN ANDRÉS', 0, 1, 1),
            ('GUAYZIMI', 0, 1, 1),
            ('ZURMI', 0, 1, 1),
            ('NUEVO PARAÍSO', 0, 1, 1),
            ('28 DE MAYO (SAN JOSÉ DE YACUAMBI)', 0, 1, 1),
            ('LA PAZ', 0, 1, 1),
            ('TUTUPALI', 0, 1, 1),
            ('(YANZATZA) YANTZAZA (YANZATZA)', 0, 1, 1),
            ('(YANZATZA) CHICAÑA', 0, 1, 1),
            ('(YANZATZA) EL PANGUI', 0, 1, 1),
            ('(YANZATZA) LOS ENCUENTROS', 0, 1, 1),
            ('EL PANGUI', 0, 1, 1),
            ('EL GUISME', 0, 1, 1),
            ('PACHICUTZA', 0, 1, 1),
            ('TUNDAYME', 0, 1, 1),
            ('ZUMBI', 0, 1, 1),
            ('PAQUISHA', 0, 1, 1),
            ('TRIUNFO-DORADO', 0, 1, 1),
            ('PANGUINTZA', 0, 1, 1),
            ('PALANDA', 0, 1, 1),
            ('EL PORVENIR DEL CARMEN', 0, 1, 1),
            ('SAN FRANCISCO DEL VERGEL', 0, 1, 1),
            ('VALLADOLID', 0, 1, 1),
            ('LA CANELA', 0, 1, 1),
            ('PAQUISHA', 0, 1, 1),
            ('BELLAVISTA', 0, 1, 1),
            ('NUEVO QUITO', 0, 1, 1),
            ('SAN CRISTÓBAL PUERTO BAQUERIZO MORENO', 0, 1, 1),
            ('SAN CRISTÓBAL EL PROGRESO', 0, 1, 1),
            ('ISABELA PUERTO VILLAMIL', 0, 1, 1),
            ('ISABELA TOMÁS DE BERLANGA (SANTO TOMÁS)', 0, 1, 1),
            ('SANTA CRUZ PUERTO AYORA', 0, 1, 1),
            ('SANTA CRUZ BELLAVISTA', 0, 1, 1),
            ('SANTA CRUZ SANTA ROSA (INCLUYE LA ISLA BALTRA)', 0, 1, 1),
            ('LAGO AGRIO NUEVA LOJA', 0, 1, 1),
            ('LAGO AGRIO CUYABENO', 0, 1, 1),
            ('LAGO AGRIO DURENO', 0, 1, 1),
            ('LAGO AGRIO GENERAL FARFÁN', 0, 1, 1),
            ('LAGO AGRIO TARAPOA', 0, 1, 1),
            ('LAGO AGRIO EL ENO', 0, 1, 1),
            ('LAGO AGRIO PACAYACU', 0, 1, 1),
            ('LAGO AGRIO JAMBELÍ', 0, 1, 1),
            ('LAGO AGRIO SANTA CECILIA', 0, 1, 1),
            ('LAGO AGRIO AGUAS NEGRAS', 0, 1, 1),
            ('GONZALO PIZARRO EL DORADO DE CASCALES', 0, 1, 1),
            ('GONZALO PIZARRO EL REVENTADOR', 0, 1, 1),
            ('GONZALO PIZARRO GONZALO PIZARRO', 0, 1, 1),
            ('GONZALO PIZARRO LUMBAQUÍ', 0, 1, 1),
            ('GONZALO PIZARRO PUERTO LIBRE', 0, 1, 1),
            ('GONZALO PIZARRO SANTA ROSA DE SUCUMBÍOS', 0, 1, 1),
            ('PUTUMAYO PUERTO EL CARMEN DEL PUTUMAYO', 0, 1, 1),
            ('PUTUMAYO PALMA ROJA', 0, 1, 1),
            ('PUTUMAYO PUERTO BOLÍVAR (PUERTO MONTÚFAR)', 0, 1, 1),
            ('PUTUMAYO PUERTO RODRÍGUEZ', 0, 1, 1),
            ('PUTUMAYO SANTA ELENA', 0, 1, 1),
            ('SHUSHUFINDI SHUSHUFINDI', 0, 1, 1),
            ('SHUSHUFINDI LIMONCOCHA', 0, 1, 1),
            ('SHUSHUFINDI PAÑACOCHA', 0, 1, 1),
            ('SHUSHUFINDI SAN ROQUE (CAB. EN SAN VICENTE)', 0, 1, 1),
            ('SHUSHUFINDI SAN PEDRO DE LOS COFANES', 0, 1, 1),
            ('SHUSHUFINDI SIETE DE JULIO', 0, 1, 1),
            ('SUCUMBÍOS LA BONITA', 0, 1, 1),
            ('SUCUMBÍOS EL PLAYÓN DE SAN FRANCISCO', 0, 1, 1),
            ('SUCUMBÍOS LA SOFÍA', 0, 1, 1),
            ('SUCUMBÍOS ROSA FLORIDA', 0, 1, 1),
            ('SUCUMBÍOS SANTA BÁRBARA', 0, 1, 1),
            ('CASCALES EL DORADO DE CASCALES', 0, 1, 1),
            ('CASCALES SANTA ROSA DE SUCUMBÍOS', 0, 1, 1),
            ('CASCALES SEVILLA', 0, 1, 1),
            ('CUYABENO TARAPOA', 0, 1, 1),
            ('CUYABENO CUYABENO', 0, 1, 1),
            ('CUYABENO AGUAS NEGRAS', 0, 1, 1),
            ('ORELLANA PUERTO FRANCISCO DE ORELLANA (EL COCA)', 0, 1, 1),
            ('ORELLANA DAYUMA', 0, 1, 1),
            ('ORELLANA TARACOA (NUEVA ESPERANZA: YUCA)', 0, 1, 1),
            ('ORELLANA ALEJANDRO LABAKA', 0, 1, 1),
            ('ORELLANA EL DORADO', 0, 1, 1),
            ('ORELLANA EL EDÉN', 0, 1, 1),
            ('ORELLANA GARCÍA MORENO', 0, 1, 1),
            ('ORELLANA INÉS ARANGO (CAB. EN WESTERN)', 0, 1, 1),
            ('ORELLANA LA BELLEZA', 0, 1, 1),
            ('ORELLANA NUEVO PARAÍSO (CAB. EN UNIÓN', 0, 1, 1),
            ('ORELLANA SAN JOSÉ DE GUAYUSA', 0, 1, 1),
            ('ORELLANA SAN LUIS DE ARMENIA', 0, 1, 1),
            ('AGUARICO TIPITINI', 0, 1, 1),
            ('AGUARICO NUEVO ROCAFUERTE', 0, 1, 1),
            ('AGUARICO CAPITÁN AUGUSTO RIVADENEYRA', 0, 1, 1),
            ('AGUARICO CONONACO', 0, 1, 1),
            ('AGUARICO SANTA MARÍA DE HUIRIRIMA', 0, 1, 1),
            ('AGUARICO TIPUTINI', 0, 1, 1),
            ('AGUARICO YASUNÍ', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS LA JOYA DE LOS SACHAS', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS ENOKANQUI', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS POMPEYA', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS SAN CARLOS', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS SAN SEBASTIÁN DEL COCA', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS LAGO SAN PEDRO', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS RUMIPAMBA', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS TRES DE NOVIEMBRE', 0, 1, 1),
            ('LA JOYA DE LOS SACHAS UNIÓN MILAGREÑA', 0, 1, 1),
            ('LORETO LORETO', 0, 1, 1),
            ('LORETO AVILA (CAB. EN HUIRUNO)', 0, 1, 1),
            ('LORETO PUERTO MURIALDO', 0, 1, 1),
            ('LORETO SAN JOSÉ DE PAYAMINO', 0, 1, 1),
            ('LORETO SAN JOSÉ DE DAHUANO', 0, 1, 1),
            ('LORETO SAN VICENTE DE HUATICOCHA', 0, 1, 1),
            ('SANTO DOMINGO ABRAHAM CALAZACÓN', 0, 1, 1),
            ('SANTO DOMINGO BOMBOLÍ', 0, 1, 1),
            ('SANTO DOMINGO CHIGUILPE', 0, 1, 1),
            ('SANTO DOMINGO RÍO TOACHI', 0, 1, 1),
            ('SANTO DOMINGO RÍO VERDE', 0, 1, 1),
            ('SANTO DOMINGO SANTO DOMINGO DE LOS COLORADOS', 0, 1, 1),
            ('SANTO DOMINGO ZARACAY', 0, 1, 1),
            ('SANTO DOMINGO SANTO DOMINGO DE LOS COLORADOS', 0, 1, 1),
            ('SANTO DOMINGO ALLURIQUÍN', 0, 1, 1),
            ('SANTO DOMINGO PUERTO LIMÓN', 0, 1, 1),
            ('SANTO DOMINGO LUZ DE AMÉRICA', 0, 1, 1),
            ('SANTO DOMINGO SAN JACINTO DEL BÚA', 0, 1, 1),
            ('SANTO DOMINGO VALLE HERMOSO', 0, 1, 1),
            ('SANTO DOMINGO EL ESFUERZO', 0, 1, 1),
            ('SANTO DOMINGO SANTA MARÍA DEL TOACHI', 0, 1, 1),
            ('BALLENITA', 0, 1, 1),
            ('SANTA ELENA', 0, 1, 1),
            ('SANTA ELENA', 0, 1, 1),
            ('ATAHUALPA', 0, 1, 1),
            ('COLONCHE', 0, 1, 1),
            ('CHANDUY', 0, 1, 1),
            ('MANGLARALTO', 0, 1, 1),
            ('SIMÓN BOLÍVAR (JULIO MORENO)', 0, 1, 1),
            ('SAN JOSÉ DE ANCÓN', 0, 1, 1),
            ('LA LIBERTAD', 0, 1, 1),
            ('CARLOS ESPINOZA LARREA', 0, 1, 1),
            ('GRAL. ALBERTO ENRÍQUEZ GALLO', 0, 1, 1),
            ('VICENTE ROCAFUERTE', 0, 1, 1),
            ('SANTA ROSA', 0, 1, 1),
            ('SALINAS', 0, 1, 1),
            ('ANCONCITO', 0, 1, 1),
            ('JOSÉ LUIS TAMAYO (MUEY)', 0, 1, 1),
            ('LAS GOLONDRINAS LAS GOLONDRINAS', 0, 1, 1),
            ('MANGA DEL CURA MANGA DEL CURA', 0, 1, 1),
            ('EL PIEDRERO EL PIEDRERO', 0, 1, 1);
        ");
    }

    public function down()
    {
        //
    }
}
