<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InsertDataToListaRetencionTable extends Migration
{
    public function up()
    {
        Schema::table('lista_retencion', function (Blueprint $table) {
            DB::table('lista_retencion')->insert([
                ['id' => '1', 'nombre' => 'HONORARIOS PROFESIONALES Y DEMáS PAGOS POR SERVICIOS RELACIONADOS CON EL TíTULO PROFESIONAL', 'codigo' => '303', 'porcentaje' => 10, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '2', 'nombre' => 'SERVICIOS PREDOMINA EL INTELECTO NO RELACIONADOS CON EL TíTULO PROFESIONAL', 'codigo' => '304', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '3', 'nombre' => 'COMISIONES Y DEMáS PAGOS POR SERVICIOS PREDOMINA INTELECTO NO RELACIONADOS CON EL TíTULO PROFESIONAL', 'codigo' => '304A', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '4', 'nombre' => 'PAGOS A NOTARIOS Y REGISTRADORES DE LA PROPIEDAD Y MERCANTIL POR SUS ACTIVIDADES EJERCIDAS COMO TALES', 'codigo' => '304B', 'porcentaje' => 10, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '5', 'nombre' => 'PAGOS A DEPORTISTAS, ENTRENADORES, áRBITROS, MIEMBROS DEL CUERPO TéCNICO POR SUS ACTIVIDADES EJERCIDAS COMO TALES', 'codigo' => '304C', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '6', 'nombre' => 'PAGOS A ARTISTAS POR SUS ACTIVIDADES EJERCIDAS COMO TALES', 'codigo' => '304D', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '7', 'nombre' => 'HONORARIOS Y DEMáS PAGOS POR SERVICIOS DE DOCENCIA', 'codigo' => '304E', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '8', 'nombre' => 'SERVICIOS PREDOMINA LA MANO DE OBRA', 'codigo' => '307', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '9', 'nombre' => 'Utilización o aprovechamiento de la imagen o renombre', 'codigo' => '308', 'porcentaje' => 10, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '10', 'nombre' => 'SERVICIOS PRESTADOS POR MEDIOS DE COMUNICACIóN Y AGENCIAS DE PUBLICIDAD', 'codigo' => '309', 'porcentaje' => 2.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '11', 'nombre' => 'SERVICIO DE TRANSPORTE PRIVADO DE PASAJEROS O TRANSPORTE PúBLICO O PRIVADO DE CARGA', 'codigo' => '310', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '12', 'nombre' => 'POR PAGOS A TRAVéS DE LIQUIDACIóN DE COMPRA (NIVEL CULTURAL O RUSTICIDAD) **', 'codigo' => '311', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '13', 'nombre' => 'TRANSFERENCIA DE BIENES MUEBLES DE NATURALEZA CORPORAL', 'codigo' => '312', 'porcentaje' => 1.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '14', 'nombre' => 'COMPRA DE BIENES DE ORIGEN AGRíCOLA, AVíCOLA, PECUARIO, APíCOLA, CUNíCULA, BIOACUáTICO, FORESTAL Y CARNES EN ESTADO NATURAL EFECTUADOS DIRECTAMENTE AL PRODUCTOR', 'codigo' => '312A', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '15', 'nombre' => 'REGALíAS POR CONCEPTO DE FRANQUICIAS DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL - PAGO A PERSONAS NATURALES', 'codigo' => '314A', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '16', 'nombre' => 'CáNONES, DERECHOS DE AUTOR, MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL – PAGO A PERSONAS NATURALES', 'codigo' => '314B', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '17', 'nombre' => 'REGALíAS POR CONCEPTO DE FRANQUICIAS DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL - PAGO A SOCIEDADES', 'codigo' => '314C', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '18', 'nombre' => 'CáNONES, DERECHOS DE AUTOR, MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL – PAGO A SOCIEDADES', 'codigo' => '314D', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '19', 'nombre' => 'CUOTAS DE ARRENDAMIENTO MERCANTIL, INCLUSIVE LA DE OPCIóN DE COMPRA', 'codigo' => '319', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '20', 'nombre' => 'POR ARRENDAMIENTO BIENES INMUEBLES', 'codigo' => '320', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '21', 'nombre' => 'SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)', 'codigo' => '322', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '22', 'nombre' => 'POR RENDIMIENTOS FINANCIEROS PAGADOS A NATURALES Y SOCIEDADES (NO A IFIS)', 'codigo' => '323', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '23', 'nombre' => 'Por RF: depósitos Cta. Corriente', 'codigo' => '323A', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '24', 'nombre' => 'POR RF: DEPóSITOS CTA. AHORROS SOCIEDADES', 'codigo' => '323B1', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '25', 'nombre' => 'Por RF: depósito a plazo fijo gravados', 'codigo' => '323E', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '26', 'nombre' => 'Por RF: depósito a plazo fijo exentos ***', 'codigo' => '323E2', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '27', 'nombre' => 'POR RENDIMIENTOS FINANCIEROS: OPERACIONES DE REPORTO - REPOS', 'codigo' => '323F', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '28', 'nombre' => 'Por RF: inversiones (captaciones) rendimientos distintos de aquellos pagados a IFIs', 'codigo' => '323G', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '29', 'nombre' => 'Por RF: obligaciones', 'codigo' => '323H', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '30', 'nombre' => 'Por RF: bonos convertible en acciones', 'codigo' => '323I', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '31', 'nombre' => 'Por RF: Inversiones en títulos valores en renta fija gravados ', 'codigo' => '323 M', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '32', 'nombre' => 'Por RF: Inversiones en títulos valores en renta fija exentos', 'codigo' => '323 N', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '33', 'nombre' => 'Por RF: Intereses pagados a bancos y otras entidades sometidas al control de la Superintendencia de Bancos y de la Economía Popular y Solidaria', 'codigo' => '323 O', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '34', 'nombre' => 'Por RF: Intereses pagados por entidades del sector público a favor de sujetos pasivos', 'codigo' => '323 P', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '35', 'nombre' => 'POR RF: OTROS INTERESES Y RENDIMIENTOS FINANCIEROS GRAVADOS', 'codigo' => '323Q', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '36', 'nombre' => 'POR RF: OTROS INTERESES Y RENDIMIENTOS FINANCIEROS EXENTOS', 'codigo' => '323R', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '37', 'nombre' => 'Por RF: Intereses y comisiones en operaciones de crédito entre instituciones del sistema financiero y entidades economía popular y solidaria.', 'codigo' => '324A', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '38', 'nombre' => 'Por RF: Por inversiones entre instituciones del sistema financiero y entidades economía popular y solidaria, incluso cuando el BCE actúe como intermediario.', 'codigo' => '324B', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '39', 'nombre' => 'Anticipo dividendos a residentes o establecidos en el Ecuador', 'codigo' => '325', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '40', 'nombre' => 'Dividendos anticipados préstamos accionistas, beneficiarios o partícipes a residentes o establecidos en el Ecuador', 'codigo' => '325A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '41', 'nombre' => 'Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI (Tabla art. 36 menos crédito tributario pro dividendos: julio 2015)', 'codigo' => '326', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '42', 'nombre' => 'Dividendos distribuidos a personas naturales residentes', 'codigo' => '327', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '43', 'nombre' => 'Dividendos distribuidos a sociedades residentes', 'codigo' => '328', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '44', 'nombre' => 'Dividendos distribuidos a fideicomisos residentes', 'codigo' => '329', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '45', 'nombre' => 'Dividendos gravados distribuidos en acciones (reinversión de utilidades sin derecho a reducción tarifa IR)', 'codigo' => '330', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '46', 'nombre' => 'Dividendos exentos distribuidos en acciones (reinversión de utilidades con derecho a reducción tarifa IR) ', 'codigo' => '331', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '47', 'nombre' => 'OTRAS COMPRAS DE BIENES Y SERVICIOS NO SUJETAS A RETENCIóN', 'codigo' => '332', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '48', 'nombre' => 'Enajenación de derechos representativos de capital y otros derechos exentos (mayo 2016)', 'codigo' => '332A', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '49', 'nombre' => 'Compra de bienes inmuebles', 'codigo' => '332B', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '50', 'nombre' => 'Transporte público de pasajeros', 'codigo' => '332C', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '51', 'nombre' => 'Pagos en el país por transporte de pasajeros o transporte internacional de carga, a compañías nacionales o extranjeras de aviación o marítimas', 'codigo' => '332D', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '52', 'nombre' => 'Valores entregados por las cooperativas de transporte a sus socios', 'codigo' => '332E', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '53', 'nombre' => 'Compraventa de divisas distintas al dólar de los Estados Unidos de América', 'codigo' => '332F', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '54', 'nombre' => 'Pagos con tarjeta de crédito ', 'codigo' => '332G', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '55', 'nombre' => 'Pago al exterior tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo RECAP', 'codigo' => '332H', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '56', 'nombre' => 'Enajenación de derechos representativos de capital y otros derechos cotizados en bolsa ecuatoriana', 'codigo' => '333', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '57', 'nombre' => 'Enajenación de derechos representativos de capital y otros derechos no cotizados en bolsa ecuatoriana', 'codigo' => '334', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '58', 'nombre' => 'POR LOTERíAS, RIFAS, APUESTAS Y SIMILARES', 'codigo' => '335', 'porcentaje' => 8, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '59', 'nombre' => 'Por venta de combustibles a comercializadoras', 'codigo' => '336', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '60', 'nombre' => 'Por venta de combustibles a distribuidores', 'codigo' => '337', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '61', 'nombre' => 'Compra local de banano a productor', 'codigo' => '338', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '62', 'nombre' => 'Liquidación impuesto único a la venta local de banano de producción propia', 'codigo' => '339', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '63', 'nombre' => 'Impuesto único a la exportación de banano de producción propia - componente 1', 'codigo' => '340', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '64', 'nombre' => 'IMPUESTO úNICO A LA EXPORTACIóN DE BANANO DE PRODUCCIóN PROPIA - COMPONENTE 2', 'codigo' => '341', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '65', 'nombre' => 'Impuesto único a la exportación de banano producido por terceros', 'codigo' => '342', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '66', 'nombre' => 'POR ENERGíA ELéCTRICA', 'codigo' => '343A', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '67', 'nombre' => 'POR ACTIVIDADES DE CONSTRUCCIóN DE OBRA MATERIAL INMUEBLE, URBANIZACIóN, LOTIZACIóN O ACTIVIDADES SIMILARES', 'codigo' => '343B', 'porcentaje' => 1.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '68', 'nombre' => 'OTRAS RETENCIONES APLICABLES EL 2.75%', 'codigo' => '3440', 'porcentaje' => 2.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '69', 'nombre' => 'Pago local tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo RECAP', 'codigo' => '344A', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '70', 'nombre' => 'Ganancias de capital', 'codigo' => '346A', 'porcentaje' => 2, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '71', 'nombre' => 'Donaciones en dinero -Impuesto a la donaciones ', 'codigo' => '347', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '72', 'nombre' => 'Retención a cargo del propio sujeto pasivo por la exportación de concentrados y/o elementos metálicos', 'codigo' => '348', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '73', 'nombre' => 'Retención a cargo del propio sujeto pasivo por la comercialización de productos forestales', 'codigo' => '349', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '74', 'nombre' => 'Pago al exterior - Rentas Inmobiliarias', 'codigo' => '500', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '75', 'nombre' => 'Pago al exterior - Beneficios Empresariales', 'codigo' => '501', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '76', 'nombre' => 'Pago al exterior - Servicios Empresariales', 'codigo' => '502', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '77', 'nombre' => 'Pago al exterior - Navegación Marítima y/o aérea', 'codigo' => '503', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '78', 'nombre' => 'Pago al exterior- Dividendos distribuidos a personas naturales', 'codigo' => '504', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '79', 'nombre' => 'Pago al exterior - Dividendos a sociedades', 'codigo' => '504A', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '80', 'nombre' => 'Pago al exterior - Anticipo dividendos (excepto paraísos fiscales o de régimen de menor imposición)', 'codigo' => '504B', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '81', 'nombre' => 'Pago al exterior - Dividendos anticipados préstamos accionistas, beneficiarios o partìcipes (paraísos fiscales o regímenes de menor imposición)', 'codigo' => '504C', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '82', 'nombre' => 'Pago al exterior - Dividendos a fideicomisos', 'codigo' => '504D', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '83', 'nombre' => 'Pago al exterior - Dividendos a sociedades (paraísos fiscales)', 'codigo' => '504F', 'porcentaje' => null, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '84', 'nombre' => 'Pago al exterior - Anticipo dividendos (paraísos fiscales)', 'codigo' => '504G', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '85', 'nombre' => 'Pago al exterior - Dividendos a fideicomisos (paraísos fiscales)', 'codigo' => '504H', 'porcentaje' => 0, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '86', 'nombre' => 'PAGO AL EXTERIOR - RENDIMIENTOS FINANCIEROS', 'codigo' => '505', 'porcentaje' => 13, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '87', 'nombre' => 'Pago al exterior – Intereses de créditos de Instituciones Financieras del exterior', 'codigo' => '505A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '88', 'nombre' => 'Pago al exterior – Intereses de créditos de gobierno a gobierno', 'codigo' => '505B', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '89', 'nombre' => 'Pago al exterior – Intereses de créditos de organismos multilaterales', 'codigo' => '505C', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '90', 'nombre' => 'Pago al exterior - Intereses por financiamiento de proveedores externos', 'codigo' => '505D', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '91', 'nombre' => 'Pago al exterior - Intereses de otros créditos externos', 'codigo' => '505E', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '92', 'nombre' => 'PAGO AL EXTERIOR - OTROS INTERESES Y RENDIMIENTOS FINANCIEROS', 'codigo' => '505F', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '93', 'nombre' => 'Pago al exterior - Cánones, derechos de autor, marcas, patentes y similares', 'codigo' => '509', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '94', 'nombre' => 'Pago al exterior - Regalías por concepto de franquicias', 'codigo' => '509A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '95', 'nombre' => 'Pago al exterior - Ganancias de capital', 'codigo' => '510', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '96', 'nombre' => 'Pago al exterior - Servicios profesionales independientes', 'codigo' => '511', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '97', 'nombre' => 'Pago al exterior - Servicios profesionales dependientes', 'codigo' => '512', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '98', 'nombre' => 'Pago al exterior - Artistas', 'codigo' => '513', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '99', 'nombre' => 'Pago al exterior - Deportistas', 'codigo' => '513A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '100', 'nombre' => 'Pago al exterior - Participación de consejeros', 'codigo' => '514', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '101', 'nombre' => 'Pago al exterior - Entretenimiento Público', 'codigo' => '515', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '102', 'nombre' => 'Pago al exterior - Pensiones', 'codigo' => '516', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '103', 'nombre' => 'Pago al exterior - Reembolso de Gastos', 'codigo' => '517', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '104', 'nombre' => 'Pago al exterior - Funciones Públicas', 'codigo' => '518', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '105', 'nombre' => 'Pago al exterior - Estudiantes', 'codigo' => '519', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '106', 'nombre' => 'Pago al exterior - Otros conceptos de ingresos gravados', 'codigo' => '520', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '107', 'nombre' => 'Pago al exterior - Pago a proveedores de servicios hoteleros y turísticos en el exterior', 'codigo' => '520A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '108', 'nombre' => 'PAGO AL EXTERIOR - ARRENDAMIENTOS MERCANTIL INTERNACIONAL', 'codigo' => '520B', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '109', 'nombre' => 'Pago al exterior - Comisiones por exportaciones y por promoción de turismo receptivo', 'codigo' => '520D', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '110', 'nombre' => 'Pago al exterior - Por las empresas de transporte marítimo o aéreo y por empresas pesqueras de alta mar, por su actividad.', 'codigo' => '520E', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '111', 'nombre' => 'Pago al exterior - Por las agencias internacionales de prensa', 'codigo' => '520F', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '112', 'nombre' => 'Pago al exterior - Contratos de fletamento de naves para empresas de transporte aéreo o marítimo internacional', 'codigo' => '520G', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '113', 'nombre' => 'Pago al exterior - Enajenación de derechos representativos de capital y otros derechos ', 'codigo' => '521', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '114', 'nombre' => 'Pago al exterior - Servicios técnicos, administrativos o de consultoría y regalías con convenio de doble tributación', 'codigo' => '522A', 'porcentaje' => 5, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '115', 'nombre' => 'PAGO AL EXTERIOR - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES) CON CONVENIO DE DOBLE TRIBUTACIóN', 'codigo' => '523A', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '116', 'nombre' => 'Pago al exterior - Otros pagos al exterior no sujetos a retención ', 'codigo' => '524', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '117', 'nombre' => 'Pago al exterior - Donaciones en dinero -Impuesto a la donaciones', 'codigo' => '525', 'porcentaje' => 22, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '118', 'nombre' => 'OTRAS RETENCIONES APLICABLES A OTROS PORCENTAJES ( INCLUYEN RETENCIONES AL REGIMEN MICROEMPRESARIAL)', 'codigo' => '346', 'porcentaje' => 2.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '119', 'nombre' => 'OTRAS RETENCIONES APLICABLES A OTROS PORCENTAJES ( INCLUYEN RETENCIONES AL REGIMEN MICROEMPRESARIAL)', 'codigo' => '346', 'porcentaje' => 10, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '120', 'nombre' => 'OTRAS RETENCIONES APLICABLES EL 1%', 'codigo' => '343', 'porcentaje' => 1, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '121', 'nombre' => 'RETENC SUMINISTROS Y MATERIALES', 'codigo' => '312', 'porcentaje' => 1.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '122', 'nombre' => 'SERVICIOS PROFESIONALES PRESTADOS POR SOCIEDADES RESIDENTES', 'codigo' => '309A', 'porcentaje' => 3, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '123', 'nombre' => 'COMISIONES PAGADAS A SOCIEDADES, NACIONALES O EXTRANJERAS RESIDENTES EN EL ECUADOR', 'codigo' => '309 B', 'porcentaje' => 3, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '124', 'nombre' => 'COMPRA DE BIENES DE ORIGEN AGRíCOLA, AVíCOLA, PECUARIO, APíCOLA, CUNíCULA, BIOACUáTICO, FORESTAL Y CARNES EN ESTADO NATURAL EFECTUADOS A COMERCIALIZADORES NO PRODUCTORES', 'codigo' => '312B', 'porcentaje' => 1.75, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '125', 'nombre' => 'SERVICIOS PROFESIONALES PRESTADOS POR SOCIEDADES RESIDENTES', 'codigo' => '303A', 'porcentaje' => 3, 'tipo_retencion_id' => '1', 'status' => true],
                ['id' => '126', 'nombre' => '10%', 'codigo' => 10, 'porcentaje' => 10, 'tipo_retencion_id' => '2', 'status' => true],
                ['id' => '127', 'nombre' => '20%', 'codigo' => 20, 'porcentaje' => 20, 'tipo_retencion_id' => '2', 'status' => true],
                ['id' => '128', 'nombre' => '30%', 'codigo' => 30, 'porcentaje' => 30, 'tipo_retencion_id' => '2', 'status' => true],
                ['id' => '129', 'nombre' => '50%', 'codigo' => 50, 'porcentaje' => 50, 'tipo_retencion_id' => '2', 'status' => true],
                ['id' => '130', 'nombre' => '70%', 'codigo' => 70, 'porcentaje' => 70, 'tipo_retencion_id' => '2', 'status' => true],
                ['id' => '131', 'nombre' => '100%', 'codigo' => 100, 'porcentaje' => 100, 'tipo_retencion_id' => '2', 'status' => true]
            ]);
        });
    }

    public function down()
    {
        Schema::table('lista_retencion', function (Blueprint $table) {
            //
        });
    }
}
