<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InsertDataCiudadWithSql extends Migration
{
    public function up()
    {
        DB::statement("
            INSERT INTO ciudad (nombre, defecto, parroquia_id, status) VALUES
            ('Quito', 1, 1, 1),
            ('Guayaquil', 0, 1, 1),
            ('Cuenca', 0, 1, 1),
            ('Santo Domingo', 0, 1, 1),
            ('Durán', 0, 1, 1),
            ('Portoviejo', 0, 1, 1),
            ('Machala', 0, 1, 1),
            ('Manta', 0, 1, 1),
            ('Loja', 0, 1, 1),
            ('Quevedo', 0, 1, 1),
            ('Ambato', 0, 1, 1),
            ('Riobamba', 0, 1, 1),
            ('Daule', 0, 1, 1),
            ('Milagro', 0, 1, 1),
            ('Ibarra', 0, 1, 1),
            ('Esmeraldas', 0, 1, 1),
            ('La Libertad', 0, 1, 1),
            ('Babahoyo', 0, 1, 1),
            ('Sangolquí', 0, 1, 1),
            ('Latacunga', 0, 1, 1),
            ('Samborondón', 0, 1, 1),
            ('Montecristi', 0, 1, 1),
            ('Pasaje', 0, 1, 1),
            ('Santa Rosa', 0, 1, 1),
            ('Tulcán', 0, 1, 1),
            ('Huaquillas', 0, 1, 1),
            ('Nueva Loja', 0, 1, 1),
            ('Chone', 0, 1, 1),
            ('Santa Elena', 0, 1, 1),
            ('El Carmen', 0, 1, 1),
            ('El Coca', 0, 1, 1),
            ('General Villamil', 0, 1, 1),
            ('Buena Fe', 0, 1, 1),
            ('Jipijapa', 0, 1, 1),
            ('Cayambe', 0, 1, 1),
            ('Velasco Ibarra', 0, 1, 1),
            ('Otavalo', 0, 1, 1),
            ('Ventanas', 0, 1, 1),
            ('El Triunfo', 0, 1, 1),
            ('La Troncal', 0, 1, 1),
            ('Naranjal', 0, 1, 1),
            ('Azogues', 0, 1, 1),
            ('La Concordia', 0, 1, 1),
            ('Salinas', 0, 1, 1),
            ('Vinces', 0, 1, 1),
            ('Naranjito', 0, 1, 1),
            ('Puyo', 0, 1, 1),
            ('Balzar', 0, 1, 1),
            ('La Maná', 0, 1, 1),
            ('Rosa Zárate', 0, 1, 1),
            ('Guaranda', 0, 1, 1),
            ('Tena', 0, 1, 1),
            ('San Lorenzo', 0, 1, 1),
            ('Jaramijó', 0, 1, 1),
            ('Pedernales', 0, 1, 1),
            ('Catamayo', 0, 1, 1),
            ('El Guabo', 0, 1, 1),
            ('Atuntaqui', 0, 1, 1),
            ('Pedro Carbo', 0, 1, 1),
            ('Machachi', 0, 1, 1),
            ('', 0, 1, 1),
            ('', 0, 1, 1),
            ('Valencia', 0, 1, 1),
            ('Yaguachi', 0, 1, 1),
            ('Macas', 0, 1, 1),
            ('Bahía de Caráquez', 0, 1, 1),
            ('Arenillas', 0, 1, 1),
            ('Calceta', 0, 1, 1),
            ('Atacames', 0, 1, 1),
            ('Piñas', 0, 1, 1),
            ('Zamora', 0, 1, 1),
            ('San Miguel de Salcedo', 0, 1, 1),
            ('Lomas de Sargentillo', 0, 1, 1),
            ('Shushufindi', 0, 1, 1),
            ('Montalvo', 0, 1, 1),
            ('Pujilí', 0, 1, 1),
            ('La Joya de los Sachas', 0, 1, 1),
            ('San Gabriel', 0, 1, 1),
            ('Baños de Agua Santa', 0, 1, 1),
            ('Gualaceo', 0, 1, 1),
            ('Salitre', 0, 1, 1),
            ('Yantzaza', 0, 1, 1),
            ('Cariamanga', 0, 1, 1),
            ('Cañar', 0, 1, 1),
            ('Tabacundo', 0, 1, 1),
            ('Balao', 0, 1, 1),
            ('Puerto Ayora', 0, 1, 1),
            ('Puerto López', 0, 1, 1),
            ('Macará', 0, 1, 1),
            ('Santa Ana', 0, 1, 1),
            ('Rocafuerte', 0, 1, 1),
            ('Cumandá', 0, 1, 1),
            ('Pelileo', 0, 1, 1),
            ('Tosagua', 0, 1, 1),
            ('Santa Lucía', 0, 1, 1),
            ('Sucúa', 0, 1, 1),
            ('Cotacachi', 0, 1, 1),
            ('San Vicente', 0, 1, 1),
            ('Palestina', 0, 1, 1),
            ('Camilo Ponce Enríquez', 0, 1, 1),
            ('Narcisa de Jesús', 0, 1, 1),
            ('Zaruma', 0, 1, 1),
            ('Saquisilí', 0, 1, 1),
            ('Píllaro', 0, 1, 1),
            ('Portovelo', 0, 1, 1),
            ('Puebloviejo', 0, 1, 1),
            ('Mocache', 0, 1, 1),
            ('Gualaquiza', 0, 1, 1),
            ('Guano', 0, 1, 1),
            ('San Miguel', 0, 1, 1),
            ('Paute', 0, 1, 1),
            ('Simón Bolívar', 0, 1, 1),
            ('Flavio Alfaro', 0, 1, 1),
            ('Isidro Ayora', 0, 1, 1),
            ('Caluma', 0, 1, 1),
            ('Catacocha', 0, 1, 1),
            ('Coronel Marcelino Maridueña', 0, 1, 1),
            ('Paján', 0, 1, 1),
            ('Colimes', 0, 1, 1),
            ('Archidona', 0, 1, 1),
            ('Junín', 0, 1, 1),
            ('Puerto Baquerizo Moreno', 0, 1, 1),
            ('Palenque', 0, 1, 1),
            ('Catarama', 0, 1, 1),
            ('Pedro Vicente Maldonado', 0, 1, 1),
            ('Echeandía', 0, 1, 1),
            ('Baba', 0, 1, 1),
            ('Bucay', 0, 1, 1),
            ('Sucre', 0, 1, 1),
            ('Santa Isabel', 0, 1, 1),
            ('Quinsaloma', 0, 1, 1),
            ('Alausí', 0, 1, 1),
            ('Jujan', 0, 1, 1),
            ('Alamor', 0, 1, 1),
            ('Pimampiro', 0, 1, 1),
            ('Palora', 0, 1, 1),
            ('Biblián', 0, 1, 1),
            ('Muisne', 0, 1, 1),
            ('Chambo', 0, 1, 1),
            ('San Miguel de Los Bancos', 0, 1, 1),
            ('Loreto', 0, 1, 1),
            ('El Pangui', 0, 1, 1),
            ('Jama', 0, 1, 1),
            ('El Tambo', 0, 1, 1),
            ('El Ángel', 0, 1, 1),
            ('Marcabelí', 0, 1, 1),
            ('Valdez', 0, 1, 1),
            ('Saraguro', 0, 1, 1),
            ('Balsas', 0, 1, 1),
            ('Huaca', 0, 1, 1),
            ('Celica', 0, 1, 1),
            ('Urcuquí', 0, 1, 1),
            ('Chordeleg', 0, 1, 1),
            ('Pichincha', 0, 1, 1),
            ('Chimbo', 0, 1, 1),
            ('El Chaco', 0, 1, 1),
            ('Girón', 0, 1, 1),
            ('Pallatanga', 0, 1, 1),
            ('Bandera de Morona Santiago Zumba', 0, 1, 1),
            ('Sígsig', 0, 1, 1),
            ('Rioverde', 0, 1, 1),
            ('Gral. Leonidas Plaza Gutiérrez (Limón)', 0, 1, 1),
            ('Puerto Quito', 0, 1, 1),
            ('Chunchi', 0, 1, 1),
            ('Cevallos', 0, 1, 1),
            ('Mira', 0, 1, 1),
            ('Zapotillo', 0, 1, 1),
            ('Bolívar', 0, 1, 1),
            ('Quero', 0, 1, 1),
            ('Chillanes', 0, 1, 1),
            ('Guamote', 0, 1, 1),
            ('Zumbi', 0, 1, 1),
            ('Sigchos', 0, 1, 1),
            ('Villa La Unión', 0, 1, 1),
            ('Puerto Villamil', 0, 1, 1),
            ('Olmedo', 0, 1, 1),
            ('Pindal', 0, 1, 1),
            ('Guayzimi', 0, 1, 1),
            ('Patate', 0, 1, 1),
            ('El Dorado de Cascales', 0, 1, 1),
            ('Arajuno', 0, 1, 1),
            ('Palanda', 0, 1, 1),
            ('Santiago de Méndez', 0, 1, 1),
            ('Lumbaqui', 0, 1, 1),
            ('Amaluza', 0, 1, 1),
            ('Puerto El Carmen de Putumayo', 0, 1, 1),
            ('Las Naves', 0, 1, 1),
            ('Gonzanamá', 0, 1, 1),
            ('Baeza', 0, 1, 1),
            ('El Corazón', 0, 1, 1),
            ('Taisha', 0, 1, 1),
            ('Santa Clara', 0, 1, 1),
            ('Paccha', 0, 1, 1),
            ('Tarapoa', 0, 1, 1),
            ('28 de Mayo', 0, 1, 1),
            ('San Juan Bosco', 0, 1, 1),
            ('Paquisha', 0, 1, 1),
            ('La Victoria', 0, 1, 1),
            ('Tisaleo', 0, 1, 1),
            ('Mocha', 0, 1, 1),
            ('Penipe', 0, 1, 1),
            ('San Fernando', 0, 1, 1),
            ('Logroño', 0, 1, 1),
            ('Chaguarpamba', 0, 1, 1),
            ('Huamboya', 0, 1, 1),
            ('Nabón', 0, 1, 1),
            ('Carlos Julio Arosemena Tola', 0, 1, 1),
            ('Guachapala', 0, 1, 1),
            ('Santiago', 0, 1, 1),
            ('Pablo Sexto', 0, 1, 1),
            ('Suscal', 0, 1, 1),
            ('Oña', 0, 1, 1),
            ('Quilanga', 0, 1, 1),
            ('Chilla', 0, 1, 1),
            ('Sozoranga', 0, 1, 1),
            ('Pucará', 0, 1, 1),
            ('Mera', 0, 1, 1),
            ('La Bonita', 0, 1, 1),
            ('Olmedo', 0, 1, 1),
            ('Sevilla de Oro', 0, 1, 1),
            ('Tiputini', 0, 1, 1),
            ('Déleg', 0, 1, 1),
            ('El Pan', 0, 1, 1);
        ");
    }

    public function down()
    {
        //
    }
}
