<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InsertDataCountryWithSql extends Migration
{
    public function up()
    {
        DB::statement("
            INSERT INTO country (nombre, defecto, codigo_pais, codigo_llamada, status) VALUES
            ('Ecuador', 1, '593', '+593', 1),
            ('Estados Unidos', 0, '1', '+1', 1),
            ('Afganistán', 0, null, null, 1),
            ('Alemania', 0, null, null, 1),
            ('Andorra', 0, null, null, 1),
            ('Albania', 0, null, null, 1),
            ('Angola', 0, null, null, 1),
            ('Antigua y Barbuda', 0, null, null, 1),
            ('Arabia Saudita', 0, null, null, 1),
            ('Argelia', 0, null, null, 1),
            ('Argentina', 0, null, null, 1),
            ('Armenia', 0, null, null, 1),
            ('Australia', 0, null, null, 1),
            ('Austria', 0, null, null, 1),
            ('Azerbaiyán', 0, null, null, 1),
            ('Bahamas', 0, null, null, 1),
            ('Bangladés', 0, null, null, 1),
            ('Barbados', 0, null, null, 1),
            ('Baréin', 0, null, null, 1),
            ('Bélgica', 0, null, null, 1),
            ('Belice', 0, null, null, 1),
            ('Benín', 0, null, null, 1),
            ('Bielorrusia', 0, null, null, 1),
            ('Birmania', 0, null, null, 1),
            ('Bolivia', 0, null, null, 1),
            ('Bosnia y Herzegovina', 0, null, null, 1),
            ('Botsuana', 0, null, null, 1),
            ('Brasil', 0, null, null, 1),
            ('Brunéi', 0, null, null, 1),
            ('Bulgaria', 0, null, null, 1),
            ('Burkina Faso', 0, null, null, 1),
            ('Burundi', 0, null, null, 1),
            ('Bután', 0, null, null, 1),
            ('Cabo Verde', 0, null, null, 1),
            ('Camboya', 0, null, null, 1),
            ('Camerún', 0, null, null, 1),
            ('Canadá', 0, null, null, 1),
            ('Catar', 0, null, null, 1),
            ('Chad', 0, null, null, 1),
            ('Chile', 0, null, null, 1),
            ('China', 0, null, null, 1),
            ('Chipre', 0, null, null, 1),
            ('Ciudad del Vaticano', 0, null, null, 1),
            ('Colombia', 0, null, null, 1),
            ('Comoras', 0, null, null, 1),
            ('Corea del Norte', 0, null, null, 1),
            ('Corea del Sur', 0, null, null, 1),
            ('Costa de Marfil', 0, null, null, 1),
            ('Costa Rica', 0, null, null, 1),
            ('Croacia', 0, null, null, 1),
            ('Cuba', 0, null, null, 1),
            ('Dinamarca', 0, null, null, 1),
            ('Dominica', 0, null, null, 1),
            ('Egipto', 0, null, null, 1),
            ('El Salvador', 0, null, null, 1),
            ('Emiratos Árabes Unidos', 0, null, null, 1),
            ('Eritrea', 0, null, null, 1),
            ('Eslovaquia', 0, null, null, 1),
            ('Eslovenia', 0, null, null, 1),
            ('España', 0, null, null, 1),
            ('Estonia', 0, null, null, 1),
            ('Etiopía', 0, null, null, 1),
            ('Filipinas', 0, null, null, 1),
            ('Finlandia', 0, null, null, 1),
            ('Fiyi', 0, null, null, 1),
            ('Francia', 0, null, null, 1),
            ('Gabón', 0, null, null, 1),
            ('Gambia', 0, null, null, 1),
            ('Georgia', 0, null, null, 1),
            ('Ghana', 0, null, null, 1),
            ('Granada', 0, null, null, 1),
            ('Grecia', 0, null, null, 1),
            ('Guatemala', 0, null, null, 1),
            ('Guyana', 0, null, null, 1),
            ('Guinea', 0, null, null, 1),
            ('Guinea ecuatorial', 0, null, null, 1),
            ('Guinea-Bisáu', 0, null, null, 1),
            ('Haití', 0, null, null, 1),
            ('Honduras', 0, null, null, 1),
            ('Hungría', 0, null, null, 1),
            ('India', 0, null, null, 1),
            ('Indonesia', 0, null, null, 1),
            ('Irak', 0, null, null, 1),
            ('Irán', 0, null, null, 1),
            ('Irlanda', 0, null, null, 1),
            ('Islandia', 0, null, null, 1),
            ('Islas Marshall', 0, null, null, 1),
            ('Islas Salomón', 0, null, null, 1),
            ('Israel', 0, null, null, 1),
            ('Italia', 0, null, null, 1),
            ('Jamaica', 0, null, null, 1),
            ('Japón', 0, null, null, 1),
            ('Jordania', 0, null, null, 1),
            ('Kazajistán', 0, null, null, 1),
            ('Kenia', 0, null, null, 1),
            ('Kirguistán', 0, null, null, 1),
            ('Kiribati', 0, null, null, 1),
            ('Kuwait', 0, null, null, 1),
            ('Laos', 0, null, null, 1),
            ('Lesoto', 0, null, null, 1),
            ('Letonia', 0, null, null, 1),
            ('Líbano', 0, null, null, 1),
            ('Liberia', 0, null, null, 1),
            ('Libia', 0, null, null, 1),
            ('Liechtenstein', 0, null, null, 1),
            ('Lituania', 0, null, null, 1),
            ('Luxemburgo', 0, null, null, 1),
            ('Macedonia del Norte', 0, null, null, 1),
            ('Madagascar', 0, null, null, 1),
            ('Malasia', 0, null, null, 1),
            ('Malaui', 0, null, null, 1),
            ('Maldivas', 0, null, null, 1),
            ('Maldivas', 0, null, null, 1),
            ('Malta', 0, null, null, 1),
            ('Marruecos', 0, null, null, 1),
            ('Mauricio', 0, null, null, 1),
            ('Mauritania', 0, null, null, 1),
            ('México', 0, null, null, 1),
            ('Micronesia', 0, null, null, 1),
            ('Moldavia', 0, null, null, 1),
            ('Mónaco', 0, null, null, 1),
            ('Mongolia', 0, null, null, 1),
            ('Montenegro', 0, null, null, 1),
            ('Mozambique', 0, null, null, 1),
            ('Namibia', 0, null, null, 1),
            ('Nauru', 0, null, null, 1),
            ('Nepal', 0, null, null, 1),
            ('Nicaragua', 0, null, null, 1),
            ('Níger', 0, null, null, 1),
            ('Nigeria', 0, null, null, 1),
            ('Noruega', 0, null, null, 1),
            ('Nueva Zelanda', 0, null, null, 1),
            ('Omán', 0, null, null, 1),
            ('Países Bajos', 0, null, null, 1),
            ('Pakistán', 0, null, null, 1),
            ('Palaos', 0, null, null, 1),
            ('Panamá', 0, null, null, 1),
            ('Papúa Nueva Guinea', 0, null, null, 1),
            ('Paraguay', 0, null, null, 1),
            ('Perú', 0, null, null, 1),
            ('Polonia', 0, null, null, 1),
            ('Portugal', 0, null, null, 1),
            ('Reino Unido', 0, null, null, 1),
            ('República Centroafricana', 0, null, null, 1),
            ('República Checa', 0, null, null, 1),
            ('República del Congo', 0, null, null, 1),
            ('República Democrática del Congo', 0, null, null, 1),
            ('República Dominicana', 0, null, null, 1),
            ('República Sudafricana', 0, null, null, 1),
            ('Ruanda', 0, null, null, 1),
            ('Rumanía', 0, null, null, 1),
            ('Rusia', 0, null, null, 1),
            ('Samoa', 0, null, null, 1),
            ('San Cristóbal y Nieves', 0, null, null, 1),
            ('San Marino', 0, null, null, 1),
            ('San Vicente y las Granadinas', 0, null, null, 1),
            ('Santa Lucía', 0, null, null, 1),
            ('Santo Tomé y Príncipe', 0, null, null, 1),
            ('Senegal', 0, null, null, 1),
            ('Serbia', 0, null, null, 1),
            ('Seychelles', 0, null, null, 1),
            ('Sierra Leona', 0, null, null, 1),
            ('Singapur', 0, null, null, 1),
            ('Siria', 0, null, null, 1),
            ('Somalia', 0, null, null, 1),
            ('Sri Lanka', 0, null, null, 1),
            ('Suazilandia', 0, null, null, 1),
            ('Sudán', 0, null, null, 1),
            ('Sudán del Sur', 0, null, null, 1),
            ('Suecia', 0, null, null, 1),
            ('Suiza', 0, null, null, 1),
            ('Surinam', 0, null, null, 1),
            ('Tailandia', 0, null, null, 1),
            ('Tanzania', 0, null, null, 1),
            ('Tayikistán', 0, null, null, 1),
            ('Timor Oriental', 0, null, null, 1),
            ('Togo', 0, null, null, 1),
            ('Tonga', 0, null, null, 1),
            ('Trinidad y Tobago', 0, null, null, 1),
            ('Túnez', 0, null, null, 1),
            ('Turkmenistán', 0, null, null, 1),
            ('Turquía', 0, null, null, 1),
            ('Tuvalu', 0, null, null, 1),
            ('Ucrania', 0, null, null, 1),
            ('Uganda', 0, null, null, 1),
            ('Uruguay', 0, null, null, 1),
            ('Uzbekistán', 0, null, null, 1),
            ('Vanuatu', 0, null, null, 1),
            ('Venezuela', 0, null, null, 1),
            ('Vietnam', 0, null, null, 1),
            ('Yemen', 0, null, null, 1),
            ('Yibuti', 0, null, null, 1),
            ('Zambia', 0, null, null, 1),
            ('Zimbabue', 0, null, null, 1);
        ");
    }

    public function down()
    {
        //
    }
}
